export type Product = {
  symbol: string;
  name: string;
  sector: "Technologie" | "Energie" | "Finanzen" | "Gesundheit" | "Konsum" | "Industrie" | "Rohstoffe" | "Index";
  region: "US" | "DE" | "EU" | "JP";
};

export const PRODUCTS: Product[] = [
  // US Tech
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technologie", region: "US" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technologie", region: "US" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technologie", region: "US" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Technologie", region: "US" },
  { symbol: "META", name: "Meta Platforms", sector: "Technologie", region: "US" },
  { symbol: "AMZN", name: "Amazon", sector: "Konsum", region: "US" },
  { symbol: "TSLA", name: "Tesla", sector: "Konsum", region: "US" },
  { symbol: "AMD", name: "AMD", sector: "Technologie", region: "US" },
  { symbol: "INTC", name: "Intel", sector: "Technologie", region: "US" },
  { symbol: "ORCL", name: "Oracle", sector: "Technologie", region: "US" },
  { symbol: "CRM", name: "Salesforce", sector: "Technologie", region: "US" },
  { symbol: "NFLX", name: "Netflix", sector: "Konsum", region: "US" },
  // US Finanzen / Industrie / Energie / Gesundheit
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Finanzen", region: "US" },
  { symbol: "BAC", name: "Bank of America", sector: "Finanzen", region: "US" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Finanzen", region: "US" },
  { symbol: "V", name: "Visa", sector: "Finanzen", region: "US" },
  { symbol: "MA", name: "Mastercard", sector: "Finanzen", region: "US" },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energie", region: "US" },
  { symbol: "CVX", name: "Chevron", sector: "Energie", region: "US" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Gesundheit", region: "US" },
  { symbol: "PFE", name: "Pfizer", sector: "Gesundheit", region: "US" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Gesundheit", region: "US" },
  { symbol: "BA", name: "Boeing", sector: "Industrie", region: "US" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrie", region: "US" },
  { symbol: "KO", name: "Coca-Cola", sector: "Konsum", region: "US" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Konsum", region: "US" },
  // EU / DE
  { symbol: "SAP", name: "SAP SE", sector: "Technologie", region: "DE" },
  { symbol: "SIE.DE", name: "Siemens", sector: "Industrie", region: "DE" },
  { symbol: "DBK.DE", name: "Deutsche Bank", sector: "Finanzen", region: "DE" },
  { symbol: "VOW3.DE", name: "Volkswagen", sector: "Konsum", region: "DE" },
  { symbol: "BMW.DE", name: "BMW", sector: "Konsum", region: "DE" },
  { symbol: "BAYN.DE", name: "Bayer", sector: "Gesundheit", region: "DE" },
  { symbol: "AIR.PA", name: "Airbus", sector: "Industrie", region: "EU" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technologie", region: "EU" },
  { symbol: "ADBE", name: "Adobe", sector: "Technologie", region: "US" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technologie", region: "US" },
  { symbol: "CSCO", name: "Cisco", sector: "Technologie", region: "US" },
  { symbol: "IBM", name: "IBM", sector: "Technologie", region: "US" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technologie", region: "US" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technologie", region: "US" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technologie", region: "US" },
  { symbol: "INTU", name: "Intuit", sector: "Technologie", region: "US" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technologie", region: "US" },
  { symbol: "SNOW", name: "Snowflake", sector: "Technologie", region: "US" },
  { symbol: "SHOP", name: "Shopify", sector: "Technologie", region: "US" },
  { symbol: "UBER", name: "Uber", sector: "Technologie", region: "US" },
  { symbol: "PLTR", name: "Palantir", sector: "Technologie", region: "US" },
  { symbol: "PYPL", name: "PayPal", sector: "Finanzen", region: "US" },
  { symbol: "SQ", name: "Block", sector: "Finanzen", region: "US" },
  { symbol: "AXP", name: "American Express", sector: "Finanzen", region: "US" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Finanzen", region: "US" },
  { symbol: "C", name: "Citigroup", sector: "Finanzen", region: "US" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Finanzen", region: "US" },
  { symbol: "BLK", name: "BlackRock", sector: "Finanzen", region: "US" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Finanzen", region: "US" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Gesundheit", region: "US" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Gesundheit", region: "US" },
  { symbol: "ABBV", name: "AbbVie", sector: "Gesundheit", region: "US" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Gesundheit", region: "US" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Gesundheit", region: "US" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Gesundheit", region: "US" },
  { symbol: "DHR", name: "Danaher", sector: "Gesundheit", region: "US" },
  { symbol: "COST", name: "Costco", sector: "Konsum", region: "US" },
  { symbol: "WMT", name: "Walmart", sector: "Konsum", region: "US" },
  { symbol: "HD", name: "Home Depot", sector: "Konsum", region: "US" },
  { symbol: "MCD", name: "McDonald's", sector: "Konsum", region: "US" },
  { symbol: "NKE", name: "Nike", sector: "Konsum", region: "US" },
  { symbol: "DIS", name: "Disney", sector: "Konsum", region: "US" },
  { symbol: "SBUX", name: "Starbucks", sector: "Konsum", region: "US" },
  { symbol: "PEP", name: "PepsiCo", sector: "Konsum", region: "US" },
  { symbol: "TGT", name: "Target", sector: "Konsum", region: "US" },
  { symbol: "F", name: "Ford", sector: "Konsum", region: "US" },
  { symbol: "GM", name: "General Motors", sector: "Konsum", region: "US" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrie", region: "US" },
  { symbol: "HON", name: "Honeywell", sector: "Industrie", region: "US" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrie", region: "US" },
  { symbol: "RTX", name: "RTX", sector: "Industrie", region: "US" },
  { symbol: "UPS", name: "UPS", sector: "Industrie", region: "US" },
  { symbol: "DE", name: "Deere", sector: "Industrie", region: "US" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrie", region: "US" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Energie", region: "US" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energie", region: "US" },
  { symbol: "SLB", name: "Schlumberger", sector: "Energie", region: "US" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energie", region: "US" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Rohstoffe", region: "US" },
  { symbol: "NEM", name: "Newmont", sector: "Rohstoffe", region: "US" },
  { symbol: "LIN", name: "Linde", sector: "Rohstoffe", region: "US" },
  { symbol: "APD", name: "Air Products", sector: "Rohstoffe", region: "US" },
  { symbol: "ALV.DE", name: "Allianz", sector: "Finanzen", region: "DE" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", sector: "Technologie", region: "DE" },
  { symbol: "MUV2.DE", name: "Münchener Rück", sector: "Finanzen", region: "DE" },
  { symbol: "MBG.DE", name: "Mercedes-Benz", sector: "Konsum", region: "DE" },
  { symbol: "IFX.DE", name: "Infineon", sector: "Technologie", region: "DE" },
  { symbol: "BAS.DE", name: "BASF", sector: "Rohstoffe", region: "DE" },
  { symbol: "ADS.DE", name: "Adidas", sector: "Konsum", region: "DE" },
  { symbol: "RWE.DE", name: "RWE", sector: "Energie", region: "DE" },
  { symbol: "ENR.DE", name: "Siemens Energy", sector: "Energie", region: "DE" },
  { symbol: "CON.DE", name: "Continental", sector: "Konsum", region: "DE" },
  { symbol: "HEI.DE", name: "Heidelberg Materials", sector: "Rohstoffe", region: "DE" },
  { symbol: "DHL.DE", name: "DHL Group", sector: "Industrie", region: "DE" },
  { symbol: "EOAN.DE", name: "E.ON", sector: "Energie", region: "DE" },
  { symbol: "BNP.PA", name: "BNP Paribas", sector: "Finanzen", region: "EU" },
  { symbol: "OR.PA", name: "L'Oréal", sector: "Konsum", region: "EU" },
  { symbol: "MC.PA", name: "LVMH", sector: "Konsum", region: "EU" },
  { symbol: "SAN.PA", name: "Sanofi", sector: "Gesundheit", region: "EU" },
  { symbol: "SU.PA", name: "Schneider Electric", sector: "Industrie", region: "EU" },
  { symbol: "TTE.PA", name: "TotalEnergies", sector: "Energie", region: "EU" },
  { symbol: "RMS.PA", name: "Hermès", sector: "Konsum", region: "EU" },
  { symbol: "AI.PA", name: "Air Liquide", sector: "Rohstoffe", region: "EU" },
  { symbol: "SHEL", name: "Shell", sector: "Energie", region: "EU" },
  { symbol: "AZN", name: "AstraZeneca", sector: "Gesundheit", region: "EU" },
  { symbol: "NVO", name: "Novo Nordisk", sector: "Gesundheit", region: "EU" },
  { symbol: "UL", name: "Unilever", sector: "Konsum", region: "EU" },
  { symbol: "TM", name: "Toyota", sector: "Konsum", region: "JP" },
  { symbol: "SONY", name: "Sony", sector: "Technologie", region: "JP" },
  { symbol: "MUFG", name: "Mitsubishi UFJ", sector: "Finanzen", region: "JP" },
  { symbol: "HMC", name: "Honda", sector: "Konsum", region: "JP" },
  { symbol: "IXN", name: "Global Tech ETF", sector: "Index", region: "US" },
  { symbol: "IWM", name: "Russell 2000 (IWM)", sector: "Index", region: "US" },
  { symbol: "VTI", name: "US Gesamtmarkt (VTI)", sector: "Index", region: "US" },
  { symbol: "VEA", name: "Developed Markets (VEA)", sector: "Index", region: "EU" },
  { symbol: "EFA", name: "MSCI EAFE (EFA)", sector: "Index", region: "EU" },
  { symbol: "FEZ", name: "Euro Stoxx 50 (FEZ)", sector: "Index", region: "EU" },
  // Indizes (ETF-Proxys, da Finnhub Index-Tickers oft Premium sind)
  { symbol: "SPY", name: "S&P 500 (SPY)", sector: "Index", region: "US" },
  { symbol: "QQQ", name: "NASDAQ 100 (QQQ)", sector: "Index", region: "US" },
  { symbol: "DIA", name: "Dow Jones (DIA)", sector: "Index", region: "US" },
  { symbol: "EWG", name: "DAX-Proxy (EWG)", sector: "Index", region: "DE" },
  { symbol: "EWJ", name: "Nikkei-Proxy (EWJ)", sector: "Index", region: "JP" },
];

export const SECTORS = ["Technologie", "Energie", "Finanzen", "Gesundheit", "Konsum", "Industrie", "Rohstoffe"] as const;
export const INDICES = PRODUCTS.filter((p) => p.sector === "Index");
export const BENCHMARK = "SPY";

export function findProduct(symbol: string): Product | undefined {
  return PRODUCTS.find((p) => p.symbol.toUpperCase() === symbol.toUpperCase());
}

export function searchProducts(q: string): Product[] {
  const s = q.trim().toLowerCase();
  if (!s) return PRODUCTS;
  return PRODUCTS.filter((p) => p.symbol.toLowerCase().includes(s) || p.name.toLowerCase().includes(s));
}
