export type Product = {
  symbol: string;
  name: string;
  sector: "Technologie" | "Energie" | "Finanzen" | "Gesundheit" | "Konsum" | "Industrie" | "Rohstoffe" | "Index";
  region: "US" | "DE" | "EU" | "UK" | "JP";
};

export const PRODUCTS: Product[] = [
  // US Tech
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technologie", region: "US" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technologie", region: "US" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technologie", region: "US" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Technologie", region: "US" },
  { symbol: "META", name: "Meta Platforms", sector: "Technologie", region: "US" },
  { symbol: "AMZN", name: "Amazon", sector: "Konsum", region: "US" },
  { symbol: "TSLA", name: "Tesla", sector: "Konsum", region: "US" },
  { symbol: "AMD", name: "AMD", sector: "Technologie", region: "US" },
  { symbol: "INTC", name: "Intel", sector: "Technologie", region: "US" },
  { symbol: "ORCL", name: "Oracle", sector: "Technologie", region: "US" },
  { symbol: "CRM", name: "Salesforce", sector: "Technologie", region: "US" },
  { symbol: "NFLX", name: "Netflix", sector: "Konsum", region: "US" },
  // US Finanzen / Industrie / Energie / Gesundheit
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Finanzen", region: "US" },
  { symbol: "BAC", name: "Bank of America", sector: "Finanzen", region: "US" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Finanzen", region: "US" },
  { symbol: "V", name: "Visa", sector: "Finanzen", region: "US" },
  { symbol: "MA", name: "Mastercard", sector: "Finanzen", region: "US" },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energie", region: "US" },
  { symbol: "CVX", name: "Chevron", sector: "Energie", region: "US" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Gesundheit", region: "US" },
  { symbol: "PFE", name: "Pfizer", sector: "Gesundheit", region: "US" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Gesundheit", region: "US" },
  { symbol: "BA", name: "Boeing", sector: "Industrie", region: "US" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrie", region: "US" },
  { symbol: "KO", name: "Coca-Cola", sector: "Konsum", region: "US" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Konsum", region: "US" },
  // EU / DE
  { symbol: "SAP", name: "SAP SE", sector: "Technologie", region: "DE" },
  { symbol: "SIE.DE", name: "Siemens", sector: "Industrie", region: "DE" },
  { symbol: "DBK.DE", name: "Deutsche Bank", sector: "Finanzen", region: "DE" },
  { symbol: "VOW3.DE", name: "Volkswagen", sector: "Konsum", region: "DE" },
  { symbol: "BMW.DE", name: "BMW", sector: "Konsum", region: "DE" },
  { symbol: "BAYN.DE", name: "Bayer", sector: "Gesundheit", region: "DE" },
  { symbol: "AIR.PA", name: "Airbus", sector: "Industrie", region: "EU" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technologie", region: "EU" },
  { symbol: "ADBE", name: "Adobe", sector: "Technologie", region: "US" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technologie", region: "US" },
  { symbol: "CSCO", name: "Cisco", sector: "Technologie", region: "US" },
  { symbol: "IBM", name: "IBM", sector: "Technologie", region: "US" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technologie", region: "US" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technologie", region: "US" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technologie", region: "US" },
  { symbol: "INTU", name: "Intuit", sector: "Technologie", region: "US" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technologie", region: "US" },
  { symbol: "SNOW", name: "Snowflake", sector: "Technologie", region: "US" },
  { symbol: "SHOP", name: "Shopify", sector: "Technologie", region: "US" },
  { symbol: "UBER", name: "Uber", sector: "Technologie", region: "US" },
  { symbol: "PLTR", name: "Palantir", sector: "Technologie", region: "US" },
  { symbol: "PYPL", name: "PayPal", sector: "Finanzen", region: "US" },
  { symbol: "SQ", name: "Block", sector: "Finanzen", region: "US" },
  { symbol: "AXP", name: "American Express", sector: "Finanzen", region: "US" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Finanzen", region: "US" },
  { symbol: "C", name: "Citigroup", sector: "Finanzen", region: "US" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Finanzen", region: "US" },
  { symbol: "BLK", name: "BlackRock", sector: "Finanzen", region: "US" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Finanzen", region: "US" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Gesundheit", region: "US" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Gesundheit", region: "US" },
  { symbol: "ABBV", name: "AbbVie", sector: "Gesundheit", region: "US" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Gesundheit", region: "US" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Gesundheit", region: "US" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Gesundheit", region: "US" },
  { symbol: "DHR", name: "Danaher", sector: "Gesundheit", region: "US" },
  { symbol: "COST", name: "Costco", sector: "Konsum", region: "US" },
  { symbol: "WMT", name: "Walmart", sector: "Konsum", region: "US" },
  { symbol: "HD", name: "Home Depot", sector: "Konsum", region: "US" },
  { symbol: "MCD", name: "McDonald's", sector: "Konsum", region: "US" },
  { symbol: "NKE", name: "Nike", sector: "Konsum", region: "US" },
  { symbol: "DIS", name: "Disney", sector: "Konsum", region: "US" },
  { symbol: "SBUX", name: "Starbucks", sector: "Konsum", region: "US" },
  { symbol: "PEP", name: "PepsiCo", sector: "Konsum", region: "US" },
  { symbol: "TGT", name: "Target", sector: "Konsum", region: "US" },
  { symbol: "F", name: "Ford", sector: "Konsum", region: "US" },
  { symbol: "GM", name: "General Motors", sector: "Konsum", region: "US" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrie", region: "US" },
  { symbol: "HON", name: "Honeywell", sector: "Industrie", region: "US" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrie", region: "US" },
  { symbol: "RTX", name: "RTX", sector: "Industrie", region: "US" },
  { symbol: "UPS", name: "UPS", sector: "Industrie", region: "US" },
  { symbol: "DE", name: "Deere", sector: "Industrie", region: "US" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrie", region: "US" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Energie", region: "US" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energie", region: "US" },
  { symbol: "SLB", name: "Schlumberger", sector: "Energie", region: "US" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energie", region: "US" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Rohstoffe", region: "US" },
  { symbol: "NEM", name: "Newmont", sector: "Rohstoffe", region: "US" },
  { symbol: "LIN", name: "Linde", sector: "Rohstoffe", region: "US" },
  { symbol: "APD", name: "Air Products", sector: "Rohstoffe", region: "US" },
  { symbol: "ALV.DE", name: "Allianz", sector: "Finanzen", region: "DE" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", sector: "Technologie", region: "DE" },
  { symbol: "MUV2.DE", name: "Münchener Rück", sector: "Finanzen", region: "DE" },
  { symbol: "MBG.DE", name: "Mercedes-Benz", sector: "Konsum", region: "DE" },
  { symbol: "IFX.DE", name: "Infineon", sector: "Technologie", region: "DE" },
  { symbol: "BAS.DE", name: "BASF", sector: "Rohstoffe", region: "DE" },
  { symbol: "ADS.DE", name: "Adidas", sector: "Konsum", region: "DE" },
  { symbol: "RWE.DE", name: "RWE", sector: "Energie", region: "DE" },
  { symbol: "ENR.DE", name: "Siemens Energy", sector: "Energie", region: "DE" },
  { symbol: "CON.DE", name: "Continental", sector: "Konsum", region: "DE" },
  { symbol: "HEI.DE", name: "Heidelberg Materials", sector: "Rohstoffe", region: "DE" },
  { symbol: "DHL.DE", name: "DHL Group", sector: "Industrie", region: "DE" },
  { symbol: "EOAN.DE", name: "E.ON", sector: "Energie", region: "DE" },
  { symbol: "BNP.PA", name: "BNP Paribas", sector: "Finanzen", region: "EU" },
  { symbol: "OR.PA", name: "L'Oréal", sector: "Konsum", region: "EU" },
  { symbol: "MC.PA", name: "LVMH", sector: "Konsum", region: "EU" },
  { symbol: "SAN.PA", name: "Sanofi", sector: "Gesundheit", region: "EU" },
  { symbol: "SU.PA", name: "Schneider Electric", sector: "Industrie", region: "EU" },
  { symbol: "TTE.PA", name: "TotalEnergies", sector: "Energie", region: "EU" },
  { symbol: "RMS.PA", name: "Hermès", sector: "Konsum", region: "EU" },
  { symbol: "AI.PA", name: "Air Liquide", sector: "Rohstoffe", region: "EU" },
  { symbol: "SHEL", name: "Shell", sector: "Energie", region: "UK" },
  { symbol: "AZN", name: "AstraZeneca", sector: "Gesundheit", region: "UK" },
  { symbol: "NVO", name: "Novo Nordisk", sector: "Gesundheit", region: "EU" },
  { symbol: "UL", name: "Unilever", sector: "Konsum", region: "UK" },
  { symbol: "TM", name: "Toyota", sector: "Konsum", region: "JP" },
  { symbol: "SONY", name: "Sony", sector: "Technologie", region: "JP" },
  { symbol: "MUFG", name: "Mitsubishi UFJ", sector: "Finanzen", region: "JP" },
  { symbol: "HMC", name: "Honda", sector: "Konsum", region: "JP" },
  { symbol: "IXN", name: "Global Tech ETF", sector: "Index", region: "US" },
  { symbol: "IWM", name: "Russell 2000 (IWM)", sector: "Index", region: "US" },
  { symbol: "VTI", name: "US Gesamtmarkt (VTI)", sector: "Index", region: "US" },
  { symbol: "VEA", name: "Developed Markets (VEA)", sector: "Index", region: "EU" },
  { symbol: "EFA", name: "MSCI EAFE (EFA)", sector: "Index", region: "EU" },
  { symbol: "FEZ", name: "Euro Stoxx 50 (FEZ)", sector: "Index", region: "EU" },
  // Indizes (ETF-Proxys, da Finnhub Index-Tickers oft Premium sind)
  { symbol: "SPY", name: "S&P 500 (SPY)", sector: "Index", region: "US" },
  { symbol: "QQQ", name: "NASDAQ 100 (QQQ)", sector: "Index", region: "US" },
  { symbol: "DIA", name: "Dow Jones (DIA)", sector: "Index", region: "US" },
  { symbol: "EWG", name: "DAX-Proxy (EWG)", sector: "Index", region: "DE" },
  { symbol: "EWJ", name: "Nikkei-Proxy (EWJ)", sector: "Index", region: "JP" },

  // === Erweiterte US-Tech / Halbleiter ===
  { symbol: "MU", name: "Micron Technology", sector: "Technologie", region: "US" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technologie", region: "US" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technologie", region: "US" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technologie", region: "US" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Technologie", region: "US" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Technologie", region: "US" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Technologie", region: "US" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technologie", region: "US" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Technologie", region: "US" },
  { symbol: "TSM", name: "TSMC", sector: "Technologie", region: "US" },
  { symbol: "ARM", name: "Arm Holdings", sector: "Technologie", region: "US" },
  { symbol: "AMKR", name: "Amkor Technology", sector: "Technologie", region: "US" },
  { symbol: "WDC", name: "Western Digital", sector: "Technologie", region: "US" },
  { symbol: "STX", name: "Seagate Technology", sector: "Technologie", region: "US" },
  { symbol: "SMCI", name: "Super Micro Computer", sector: "Technologie", region: "US" },
  { symbol: "DELL", name: "Dell Technologies", sector: "Technologie", region: "US" },
  { symbol: "HPQ", name: "HP Inc.", sector: "Technologie", region: "US" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technologie", region: "US" },
  { symbol: "ANET", name: "Arista Networks", sector: "Technologie", region: "US" },

  // === Software / Cloud / Cybersecurity ===
  { symbol: "CRWD", name: "CrowdStrike", sector: "Technologie", region: "US" },
  { symbol: "ZS", name: "Zscaler", sector: "Technologie", region: "US" },
  { symbol: "NET", name: "Cloudflare", sector: "Technologie", region: "US" },
  { symbol: "DDOG", name: "Datadog", sector: "Technologie", region: "US" },
  { symbol: "MDB", name: "MongoDB", sector: "Technologie", region: "US" },
  { symbol: "TEAM", name: "Atlassian", sector: "Technologie", region: "US" },
  { symbol: "WDAY", name: "Workday", sector: "Technologie", region: "US" },
  { symbol: "PATH", name: "UiPath", sector: "Technologie", region: "US" },
  { symbol: "OKTA", name: "Okta", sector: "Technologie", region: "US" },
  { symbol: "FTNT", name: "Fortinet", sector: "Technologie", region: "US" },
  { symbol: "S", name: "SentinelOne", sector: "Technologie", region: "US" },
  { symbol: "U", name: "Unity Software", sector: "Technologie", region: "US" },
  { symbol: "DOCU", name: "DocuSign", sector: "Technologie", region: "US" },
  { symbol: "ZM", name: "Zoom Video", sector: "Technologie", region: "US" },
  { symbol: "TWLO", name: "Twilio", sector: "Technologie", region: "US" },
  { symbol: "ROKU", name: "Roku", sector: "Technologie", region: "US" },
  { symbol: "SPOT", name: "Spotify", sector: "Konsum", region: "US" },
  { symbol: "PINS", name: "Pinterest", sector: "Technologie", region: "US" },
  { symbol: "SNAP", name: "Snap Inc.", sector: "Technologie", region: "US" },
  { symbol: "RBLX", name: "Roblox", sector: "Technologie", region: "US" },
  { symbol: "ABNB", name: "Airbnb", sector: "Konsum", region: "US" },
  { symbol: "LYFT", name: "Lyft", sector: "Technologie", region: "US" },
  { symbol: "DASH", name: "DoorDash", sector: "Konsum", region: "US" },
  { symbol: "RDDT", name: "Reddit", sector: "Technologie", region: "US" },
  { symbol: "APP", name: "AppLovin", sector: "Technologie", region: "US" },

  // === EV / Mobility / Clean Energy ===
  { symbol: "RIVN", name: "Rivian", sector: "Konsum", region: "US" },
  { symbol: "LCID", name: "Lucid Group", sector: "Konsum", region: "US" },
  { symbol: "NIO", name: "NIO Inc.", sector: "Konsum", region: "US" },
  { symbol: "XPEV", name: "XPeng", sector: "Konsum", region: "US" },
  { symbol: "LI", name: "Li Auto", sector: "Konsum", region: "US" },
  { symbol: "BYDDY", name: "BYD Company", sector: "Konsum", region: "US" },
  { symbol: "ENPH", name: "Enphase Energy", sector: "Energie", region: "US" },
  { symbol: "SEDG", name: "SolarEdge", sector: "Energie", region: "US" },
  { symbol: "FSLR", name: "First Solar", sector: "Energie", region: "US" },
  { symbol: "PLUG", name: "Plug Power", sector: "Energie", region: "US" },

  // === Biotech / Pharma ===
  { symbol: "MRNA", name: "Moderna", sector: "Gesundheit", region: "US" },
  { symbol: "BNTX", name: "BioNTech", sector: "Gesundheit", region: "EU" },
  { symbol: "REGN", name: "Regeneron", sector: "Gesundheit", region: "US" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Gesundheit", region: "US" },
  { symbol: "AMGN", name: "Amgen", sector: "Gesundheit", region: "US" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Gesundheit", region: "US" },
  { symbol: "CVS", name: "CVS Health", sector: "Gesundheit", region: "US" },
  { symbol: "NVAX", name: "Novavax", sector: "Gesundheit", region: "US" },

  // === China / Asien ADRs ===
  { symbol: "BABA", name: "Alibaba", sector: "Konsum", region: "JP" },
  { symbol: "JD", name: "JD.com", sector: "Konsum", region: "JP" },
  { symbol: "PDD", name: "PDD Holdings", sector: "Konsum", region: "JP" },
  { symbol: "BIDU", name: "Baidu", sector: "Technologie", region: "JP" },
  { symbol: "TCEHY", name: "Tencent", sector: "Technologie", region: "JP" },

  // === Crypto-Proxys ===
  { symbol: "COIN", name: "Coinbase", sector: "Finanzen", region: "US" },
  { symbol: "MSTR", name: "MicroStrategy", sector: "Technologie", region: "US" },
  { symbol: "MARA", name: "Marathon Digital", sector: "Technologie", region: "US" },
  { symbol: "RIOT", name: "Riot Platforms", sector: "Technologie", region: "US" },
  { symbol: "HOOD", name: "Robinhood Markets", sector: "Finanzen", region: "US" },

  // === Finanzen erweitert ===
  { symbol: "SCHW", name: "Charles Schwab", sector: "Finanzen", region: "US" },
  { symbol: "SPGI", name: "S&P Global", sector: "Finanzen", region: "US" },
  { symbol: "MCO", name: "Moody's", sector: "Finanzen", region: "US" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Finanzen", region: "US" },
  { symbol: "CME", name: "CME Group", sector: "Finanzen", region: "US" },

  // === EU / DE erweitert ===
  { symbol: "RHM.DE", name: "Rheinmetall", sector: "Industrie", region: "DE" },
  { symbol: "HEN3.DE", name: "Henkel", sector: "Konsum", region: "DE" },
  { symbol: "FRE.DE", name: "Fresenius", sector: "Gesundheit", region: "DE" },
  { symbol: "DPW.DE", name: "Deutsche Post", sector: "Industrie", region: "DE" },
  { symbol: "PAH3.DE", name: "Porsche Automobil Holding", sector: "Konsum", region: "DE" },
  { symbol: "P911.DE", name: "Porsche AG", sector: "Konsum", region: "DE" },
  { symbol: "ZAL.DE", name: "Zalando", sector: "Konsum", region: "DE" },
  { symbol: "SHL.DE", name: "Siemens Healthineers", sector: "Gesundheit", region: "DE" },
  { symbol: "MTX.DE", name: "MTU Aero Engines", sector: "Industrie", region: "DE" },
  { symbol: "ENGI.PA", name: "Engie", sector: "Energie", region: "EU" },
  { symbol: "BN.PA", name: "Danone", sector: "Konsum", region: "EU" },
  { symbol: "CAP.PA", name: "Capgemini", sector: "Technologie", region: "EU" },
  { symbol: "NESN.SW", name: "Nestlé", sector: "Konsum", region: "EU" },
  { symbol: "ROG.SW", name: "Roche", sector: "Gesundheit", region: "EU" },
  { symbol: "NOVN.SW", name: "Novartis", sector: "Gesundheit", region: "EU" },
  { symbol: "UBSG.SW", name: "UBS Group", sector: "Finanzen", region: "EU" },

  // === Sektor- & Themen-ETFs ===
  { symbol: "SMH", name: "Semiconductor ETF (SMH)", sector: "Index", region: "US" },
  { symbol: "SOXX", name: "iShares Semiconductor (SOXX)", sector: "Index", region: "US" },
  { symbol: "XLK", name: "Technology Select (XLK)", sector: "Index", region: "US" },
  { symbol: "XLF", name: "Financial Select (XLF)", sector: "Index", region: "US" },
  { symbol: "XLE", name: "Energy Select (XLE)", sector: "Index", region: "US" },
  { symbol: "XLV", name: "Health Care Select (XLV)", sector: "Index", region: "US" },
  { symbol: "XLY", name: "Consumer Discretionary (XLY)", sector: "Index", region: "US" },
  { symbol: "XLP", name: "Consumer Staples (XLP)", sector: "Index", region: "US" },
  { symbol: "XLI", name: "Industrials Select (XLI)", sector: "Index", region: "US" },
  { symbol: "XLU", name: "Utilities Select (XLU)", sector: "Index", region: "US" },
  { symbol: "XLB", name: "Materials Select (XLB)", sector: "Index", region: "US" },
  { symbol: "XLRE", name: "Real Estate Select (XLRE)", sector: "Index", region: "US" },
  { symbol: "XLC", name: "Communication Services (XLC)", sector: "Index", region: "US" },
  { symbol: "ARKK", name: "ARK Innovation (ARKK)", sector: "Index", region: "US" },
  { symbol: "ARKG", name: "ARK Genomic (ARKG)", sector: "Index", region: "US" },
  { symbol: "ARKW", name: "ARK Next Gen Internet", sector: "Index", region: "US" },
  { symbol: "TAN", name: "Solar ETF (TAN)", sector: "Index", region: "US" },
  { symbol: "ICLN", name: "Clean Energy (ICLN)", sector: "Index", region: "US" },
  { symbol: "LIT", name: "Lithium & Battery (LIT)", sector: "Index", region: "US" },
  { symbol: "URA", name: "Uranium ETF (URA)", sector: "Index", region: "US" },
  { symbol: "JETS", name: "Airline ETF (JETS)", sector: "Index", region: "US" },
  { symbol: "IBB", name: "Biotech ETF (IBB)", sector: "Index", region: "US" },
  { symbol: "XBI", name: "S&P Biotech (XBI)", sector: "Index", region: "US" },
  { symbol: "KWEB", name: "China Internet (KWEB)", sector: "Index", region: "US" },
  { symbol: "FXI", name: "China Large-Cap (FXI)", sector: "Index", region: "US" },
  { symbol: "MCHI", name: "MSCI China (MCHI)", sector: "Index", region: "US" },
  { symbol: "EEM", name: "Emerging Markets (EEM)", sector: "Index", region: "US" },
  { symbol: "VWO", name: "Vanguard Emerging (VWO)", sector: "Index", region: "US" },
  { symbol: "INDA", name: "MSCI India (INDA)", sector: "Index", region: "JP" },
  { symbol: "EWZ", name: "MSCI Brazil (EWZ)", sector: "Index", region: "US" },
  { symbol: "EWU", name: "MSCI UK (EWU)", sector: "Index", region: "UK" },

  // === Rohstoff- & Anleihen-ETFs ===
  { symbol: "GLD", name: "Gold ETF (GLD)", sector: "Index", region: "US" },
  { symbol: "IAU", name: "iShares Gold (IAU)", sector: "Index", region: "US" },
  { symbol: "SLV", name: "Silber ETF (SLV)", sector: "Index", region: "US" },
  { symbol: "USO", name: "Oil Fund (USO)", sector: "Index", region: "US" },
  { symbol: "UNG", name: "Natural Gas (UNG)", sector: "Index", region: "US" },
  { symbol: "DBC", name: "Commodity Index (DBC)", sector: "Index", region: "US" },
  { symbol: "TLT", name: "20+ Year Treasury (TLT)", sector: "Index", region: "US" },
  { symbol: "IEF", name: "7-10Y Treasury (IEF)", sector: "Index", region: "US" },
  { symbol: "SHY", name: "1-3Y Treasury (SHY)", sector: "Index", region: "US" },
  { symbol: "HYG", name: "High Yield Corp (HYG)", sector: "Index", region: "US" },
  { symbol: "LQD", name: "Investment Grade (LQD)", sector: "Index", region: "US" },
  { symbol: "BITO", name: "Bitcoin Strategy ETF", sector: "Index", region: "US" },
  { symbol: "IBIT", name: "iShares Bitcoin Trust", sector: "Index", region: "US" },
  { symbol: "ETHE", name: "Grayscale Ethereum", sector: "Index", region: "US" },

  // === Volatilität ===
  { symbol: "VIXY", name: "VIX Short-Term (VIXY)", sector: "Index", region: "US" },
  { symbol: "UVXY", name: "Ultra VIX (UVXY)", sector: "Index", region: "US" },

  // === Weitere US Large Caps / Konsum / Telekom ===
  { symbol: "T", name: "AT&T", sector: "Technologie", region: "US" },
  { symbol: "VZ", name: "Verizon", sector: "Technologie", region: "US" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Technologie", region: "US" },
  { symbol: "CMCSA", name: "Comcast", sector: "Konsum", region: "US" },
  { symbol: "PM", name: "Philip Morris", sector: "Konsum", region: "US" },
  { symbol: "MO", name: "Altria", sector: "Konsum", region: "US" },
  { symbol: "MDLZ", name: "Mondelez", sector: "Konsum", region: "US" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Konsum", region: "US" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Konsum", region: "US" },
  { symbol: "GIS", name: "General Mills", sector: "Konsum", region: "US" },
  { symbol: "HSY", name: "Hershey", sector: "Konsum", region: "US" },
  { symbol: "EL", name: "Estée Lauder", sector: "Konsum", region: "US" },
  { symbol: "LOW", name: "Lowe's", sector: "Konsum", region: "US" },
  { symbol: "TJX", name: "TJX Companies", sector: "Konsum", region: "US" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Konsum", region: "US" },
  { symbol: "MAR", name: "Marriott", sector: "Konsum", region: "US" },
  { symbol: "HLT", name: "Hilton", sector: "Konsum", region: "US" },
  { symbol: "CMG", name: "Chipotle", sector: "Konsum", region: "US" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Konsum", region: "US" },
  { symbol: "EBAY", name: "eBay", sector: "Konsum", region: "US" },
  { symbol: "ETSY", name: "Etsy", sector: "Konsum", region: "US" },
  { symbol: "CHWY", name: "Chewy", sector: "Konsum", region: "US" },

  // === Industrie & Transport ===
  { symbol: "FDX", name: "FedEx", sector: "Industrie", region: "US" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrie", region: "US" },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrie", region: "US" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrie", region: "US" },
  { symbol: "UAL", name: "United Airlines", sector: "Industrie", region: "US" },
  { symbol: "AAL", name: "American Airlines", sector: "Industrie", region: "US" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrie", region: "US" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrie", region: "US" },
  { symbol: "ETN", name: "Eaton", sector: "Industrie", region: "US" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrie", region: "US" },
  { symbol: "PH", name: "Parker Hannifin", sector: "Industrie", region: "US" },
  { symbol: "MMM", name: "3M", sector: "Industrie", region: "US" },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrie", region: "US" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrie", region: "US" },
  { symbol: "TDG", name: "TransDigm Group", sector: "Industrie", region: "US" },

  // === Energie & Versorger ===
  { symbol: "PSX", name: "Phillips 66", sector: "Energie", region: "US" },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energie", region: "US" },
  { symbol: "VLO", name: "Valero Energy", sector: "Energie", region: "US" },
  { symbol: "EOG", name: "EOG Resources", sector: "Energie", region: "US" },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energie", region: "US" },
  { symbol: "WMB", name: "Williams Companies", sector: "Energie", region: "US" },
  { symbol: "DUK", name: "Duke Energy", sector: "Energie", region: "US" },
  { symbol: "SO", name: "Southern Company", sector: "Energie", region: "US" },
  { symbol: "AEP", name: "American Electric Power", sector: "Energie", region: "US" },
  { symbol: "EXC", name: "Exelon", sector: "Energie", region: "US" },

  // === Rohstoffe / Materials ===
  { symbol: "DOW", name: "Dow Inc.", sector: "Rohstoffe", region: "US" },
  { symbol: "DD", name: "DuPont", sector: "Rohstoffe", region: "US" },
  { symbol: "PPG", name: "PPG Industries", sector: "Rohstoffe", region: "US" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Rohstoffe", region: "US" },
  { symbol: "ECL", name: "Ecolab", sector: "Rohstoffe", region: "US" },
  { symbol: "NUE", name: "Nucor", sector: "Rohstoffe", region: "US" },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Rohstoffe", region: "US" },
  { symbol: "CLF", name: "Cleveland-Cliffs", sector: "Rohstoffe", region: "US" },
  { symbol: "AA", name: "Alcoa", sector: "Rohstoffe", region: "US" },
  { symbol: "GOLD", name: "Barrick Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "AEM", name: "Agnico Eagle Mines", sector: "Rohstoffe", region: "US" },
  { symbol: "MOS", name: "Mosaic", sector: "Rohstoffe", region: "US" },
  { symbol: "CF", name: "CF Industries", sector: "Rohstoffe", region: "US" },

  // === Gesundheit erweitert ===
  { symbol: "ELV", name: "Elevance Health", sector: "Gesundheit", region: "US" },
  { symbol: "CI", name: "Cigna", sector: "Gesundheit", region: "US" },
  { symbol: "HUM", name: "Humana", sector: "Gesundheit", region: "US" },
  { symbol: "MDT", name: "Medtronic", sector: "Gesundheit", region: "US" },
  { symbol: "SYK", name: "Stryker", sector: "Gesundheit", region: "US" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Gesundheit", region: "US" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Gesundheit", region: "US" },
  { symbol: "ZBH", name: "Zimmer Biomet", sector: "Gesundheit", region: "US" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Gesundheit", region: "US" },
  { symbol: "IDXX", name: "IDEXX Laboratories", sector: "Gesundheit", region: "US" },
  { symbol: "BIIB", name: "Biogen", sector: "Gesundheit", region: "US" },
  { symbol: "ILMN", name: "Illumina", sector: "Gesundheit", region: "US" },

  // === Finanzen erweitert ===
  { symbol: "USB", name: "U.S. Bancorp", sector: "Finanzen", region: "US" },
  { symbol: "PNC", name: "PNC Financial", sector: "Finanzen", region: "US" },
  { symbol: "TFC", name: "Truist Financial", sector: "Finanzen", region: "US" },
  { symbol: "COF", name: "Capital One", sector: "Finanzen", region: "US" },
  { symbol: "DFS", name: "Discover Financial", sector: "Finanzen", region: "US" },
  { symbol: "MET", name: "MetLife", sector: "Finanzen", region: "US" },
  { symbol: "PRU", name: "Prudential Financial", sector: "Finanzen", region: "US" },
  { symbol: "AIG", name: "AIG", sector: "Finanzen", region: "US" },
  { symbol: "ALL", name: "Allstate", sector: "Finanzen", region: "US" },
  { symbol: "TRV", name: "Travelers", sector: "Finanzen", region: "US" },
  { symbol: "CB", name: "Chubb", sector: "Finanzen", region: "US" },
  { symbol: "AON", name: "Aon", sector: "Finanzen", region: "US" },
  { symbol: "MMC", name: "Marsh McLennan", sector: "Finanzen", region: "US" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", sector: "Finanzen", region: "US" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Finanzen", region: "US" },

  // === REITs ===
  { symbol: "PLD", name: "Prologis", sector: "Finanzen", region: "US" },
  { symbol: "AMT", name: "American Tower", sector: "Finanzen", region: "US" },
  { symbol: "EQIX", name: "Equinix", sector: "Finanzen", region: "US" },
  { symbol: "CCI", name: "Crown Castle", sector: "Finanzen", region: "US" },
  { symbol: "O", name: "Realty Income", sector: "Finanzen", region: "US" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Finanzen", region: "US" },
  { symbol: "PSA", name: "Public Storage", sector: "Finanzen", region: "US" },

  // === EU/UK erweitert ===
  { symbol: "VNA.DE", name: "Vonovia", sector: "Finanzen", region: "DE" },
  { symbol: "BEI.DE", name: "Beiersdorf", sector: "Konsum", region: "DE" },
  { symbol: "SRT3.DE", name: "Sartorius", sector: "Gesundheit", region: "DE" },
  { symbol: "QIA.DE", name: "Qiagen", sector: "Gesundheit", region: "DE" },
  { symbol: "PUM.DE", name: "Puma", sector: "Konsum", region: "DE" },
  { symbol: "HFG.DE", name: "HelloFresh", sector: "Konsum", region: "DE" },
  { symbol: "DB1.DE", name: "Deutsche Börse", sector: "Finanzen", region: "DE" },
  { symbol: "CBK.DE", name: "Commerzbank", sector: "Finanzen", region: "DE" },
  { symbol: "LHA.DE", name: "Lufthansa", sector: "Industrie", region: "DE" },
  { symbol: "SY1.DE", name: "Symrise", sector: "Rohstoffe", region: "DE" },
  { symbol: "ACA.PA", name: "Crédit Agricole", sector: "Finanzen", region: "EU" },
  { symbol: "GLE.PA", name: "Société Générale", sector: "Finanzen", region: "EU" },
  { symbol: "KER.PA", name: "Kering", sector: "Konsum", region: "EU" },
  { symbol: "SAF.PA", name: "Safran", sector: "Industrie", region: "EU" },
  { symbol: "DG.PA", name: "Vinci", sector: "Industrie", region: "EU" },
  { symbol: "ABBN.SW", name: "ABB", sector: "Industrie", region: "EU" },
  { symbol: "ZURN.SW", name: "Zurich Insurance", sector: "Finanzen", region: "EU" },
  { symbol: "GIVN.SW", name: "Givaudan", sector: "Rohstoffe", region: "EU" },
  { symbol: "HSBC", name: "HSBC Holdings", sector: "Finanzen", region: "UK" },
  { symbol: "BP", name: "BP plc", sector: "Energie", region: "UK" },
  { symbol: "RIO", name: "Rio Tinto", sector: "Rohstoffe", region: "UK" },
  { symbol: "BHP", name: "BHP Group", sector: "Rohstoffe", region: "UK" },
  { symbol: "GSK", name: "GSK plc", sector: "Gesundheit", region: "UK" },
  { symbol: "DEO", name: "Diageo", sector: "Konsum", region: "UK" },
  { symbol: "BTI", name: "British American Tobacco", sector: "Konsum", region: "UK" },
  { symbol: "STLA", name: "Stellantis", sector: "Konsum", region: "EU" },
  { symbol: "ENEL.MI", name: "Enel", sector: "Energie", region: "EU" },
  { symbol: "ENI.MI", name: "Eni", sector: "Energie", region: "EU" },
  { symbol: "ISP.MI", name: "Intesa Sanpaolo", sector: "Finanzen", region: "EU" },
  { symbol: "UCG.MI", name: "UniCredit", sector: "Finanzen", region: "EU" },
  { symbol: "RACE", name: "Ferrari", sector: "Konsum", region: "EU" },
  { symbol: "IBE.MC", name: "Iberdrola", sector: "Energie", region: "EU" },
  { symbol: "ITX.MC", name: "Inditex", sector: "Konsum", region: "EU" },

  // === Asien erweitert ===
  { symbol: "7203.T", name: "Toyota Motor (Tokio)", sector: "Konsum", region: "JP" },
  { symbol: "6758.T", name: "Sony Group (Tokio)", sector: "Technologie", region: "JP" },
  { symbol: "9984.T", name: "SoftBank Group", sector: "Technologie", region: "JP" },
  { symbol: "6861.T", name: "Keyence", sector: "Industrie", region: "JP" },
  { symbol: "7974.T", name: "Nintendo", sector: "Technologie", region: "JP" },
  { symbol: "NTES", name: "NetEase", sector: "Technologie", region: "JP" },
  { symbol: "TCOM", name: "Trip.com Group", sector: "Konsum", region: "JP" },
  { symbol: "BILI", name: "Bilibili", sector: "Technologie", region: "JP" },
  { symbol: "INFY", name: "Infosys", sector: "Technologie", region: "JP" },
  { symbol: "WIT", name: "Wipro", sector: "Technologie", region: "JP" },

  // === Mehr ETFs (Regional / Faktor / Income) ===
  { symbol: "VOO", name: "Vanguard S&P 500 (VOO)", sector: "Index", region: "US" },
  { symbol: "IVV", name: "iShares Core S&P 500 (IVV)", sector: "Index", region: "US" },
  { symbol: "SCHD", name: "Schwab US Dividend (SCHD)", sector: "Index", region: "US" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation", sector: "Index", region: "US" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield", sector: "Index", region: "US" },
  { symbol: "DVY", name: "iShares Select Dividend (DVY)", sector: "Index", region: "US" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium (JEPI)", sector: "Index", region: "US" },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Premium (JEPQ)", sector: "Index", region: "US" },
  { symbol: "MOAT", name: "VanEck Moat (MOAT)", sector: "Index", region: "US" },
  { symbol: "MTUM", name: "iShares Momentum (MTUM)", sector: "Index", region: "US" },
  { symbol: "QUAL", name: "iShares Quality (QUAL)", sector: "Index", region: "US" },
  { symbol: "USMV", name: "iShares Min Vol (USMV)", sector: "Index", region: "US" },
  { symbol: "VTV", name: "Vanguard Value (VTV)", sector: "Index", region: "US" },
  { symbol: "VUG", name: "Vanguard Growth (VUG)", sector: "Index", region: "US" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth", sector: "Index", region: "US" },
  { symbol: "IWD", name: "iShares Russell 1000 Value", sector: "Index", region: "US" },
  { symbol: "IJH", name: "iShares Core S&P MidCap (IJH)", sector: "Index", region: "US" },
  { symbol: "IJR", name: "iShares Core S&P SmallCap (IJR)", sector: "Index", region: "US" },
  { symbol: "VXUS", name: "Vanguard Total Intl Stock", sector: "Index", region: "EU" },
  { symbol: "ACWI", name: "MSCI ACWI (ACWI)", sector: "Index", region: "US" },
  { symbol: "EZU", name: "MSCI Eurozone (EZU)", sector: "Index", region: "EU" },
  { symbol: "EWQ", name: "MSCI France (EWQ)", sector: "Index", region: "EU" },
  { symbol: "EWI", name: "MSCI Italy (EWI)", sector: "Index", region: "EU" },
  { symbol: "EWP", name: "MSCI Spain (EWP)", sector: "Index", region: "EU" },
  { symbol: "EWL", name: "MSCI Switzerland (EWL)", sector: "Index", region: "EU" },
  { symbol: "EWN", name: "MSCI Netherlands (EWN)", sector: "Index", region: "EU" },
  { symbol: "EWA", name: "MSCI Australia (EWA)", sector: "Index", region: "JP" },
  { symbol: "EWC", name: "MSCI Canada (EWC)", sector: "Index", region: "US" },
  { symbol: "EWT", name: "MSCI Taiwan (EWT)", sector: "Index", region: "JP" },
  { symbol: "EWY", name: "MSCI South Korea (EWY)", sector: "Index", region: "JP" },
  { symbol: "EWS", name: "MSCI Singapore (EWS)", sector: "Index", region: "JP" },
  { symbol: "EWH", name: "MSCI Hong Kong (EWH)", sector: "Index", region: "JP" },
  { symbol: "EWW", name: "MSCI Mexico (EWW)", sector: "Index", region: "US" },

  // === Themen-ETFs erweitert ===
  { symbol: "BOTZ", name: "Robotics & AI (BOTZ)", sector: "Index", region: "US" },
  { symbol: "ROBO", name: "Robotics ETF (ROBO)", sector: "Index", region: "US" },
  { symbol: "AIQ", name: "AI & Tech ETF (AIQ)", sector: "Index", region: "US" },
  { symbol: "CIBR", name: "Cybersecurity ETF (CIBR)", sector: "Index", region: "US" },
  { symbol: "HACK", name: "Cyber Security (HACK)", sector: "Index", region: "US" },
  { symbol: "FINX", name: "FinTech ETF (FINX)", sector: "Index", region: "US" },
  { symbol: "BLOK", name: "Blockchain ETF (BLOK)", sector: "Index", region: "US" },
  { symbol: "GAMR", name: "Video Games (GAMR)", sector: "Index", region: "US" },
  { symbol: "HERO", name: "Esports ETF (HERO)", sector: "Index", region: "US" },
  { symbol: "DRIV", name: "Autonomous EV (DRIV)", sector: "Index", region: "US" },
  { symbol: "ITA", name: "Aerospace & Defense (ITA)", sector: "Index", region: "US" },
  { symbol: "KRE", name: "Regional Banks (KRE)", sector: "Index", region: "US" },
  { symbol: "KBE", name: "S&P Bank (KBE)", sector: "Index", region: "US" },
  { symbol: "VNQ", name: "Vanguard Real Estate (VNQ)", sector: "Index", region: "US" },
  { symbol: "GDX", name: "Gold Miners (GDX)", sector: "Index", region: "US" },
  { symbol: "GDXJ", name: "Junior Gold Miners (GDXJ)", sector: "Index", region: "US" },
  { symbol: "COPX", name: "Copper Miners (COPX)", sector: "Index", region: "US" },
  { symbol: "REMX", name: "Rare Earth Metals (REMX)", sector: "Index", region: "US" },
  { symbol: "WEAT", name: "Wheat Fund (WEAT)", sector: "Index", region: "US" },
  { symbol: "CORN", name: "Corn Fund (CORN)", sector: "Index", region: "US" },

  // === Bond / Income erweitert ===
  { symbol: "AGG", name: "iShares Core US Aggregate", sector: "Index", region: "US" },
  { symbol: "BND", name: "Vanguard Total Bond (BND)", sector: "Index", region: "US" },
  { symbol: "BNDX", name: "Vanguard Total Intl Bond", sector: "Index", region: "EU" },
  { symbol: "TIP", name: "TIPS Bond ETF (TIP)", sector: "Index", region: "US" },
  { symbol: "MUB", name: "Municipal Bond (MUB)", sector: "Index", region: "US" },
  { symbol: "EMB", name: "Emerging Markets Bond", sector: "Index", region: "US" },

  // === Krypto-bezogen erweitert ===
  { symbol: "FBTC", name: "Fidelity Wise Origin Bitcoin", sector: "Index", region: "US" },
  { symbol: "ARKB", name: "ARK 21Shares Bitcoin", sector: "Index", region: "US" },
  { symbol: "ETHA", name: "iShares Ethereum Trust", sector: "Index", region: "US" },
  { symbol: "BTBT", name: "Bit Digital", sector: "Technologie", region: "US" },
  { symbol: "CIFR", name: "Cipher Mining", sector: "Technologie", region: "US" },
  { symbol: "CLSK", name: "CleanSpark", sector: "Technologie", region: "US" },

  // === Häufig gesuchte Nachzügler ===
  { symbol: "VRT", name: "Vertiv Holdings", sector: "Industrie", region: "US" },
  { symbol: "VST", name: "Vistra Corp", sector: "Energie", region: "US" },
  { symbol: "CEG", name: "Constellation Energy", sector: "Energie", region: "US" },
  { symbol: "TLN", name: "Talen Energy", sector: "Energie", region: "US" },
  { symbol: "OKLO", name: "Oklo Inc.", sector: "Energie", region: "US" },
  { symbol: "SMR", name: "NuScale Power", sector: "Energie", region: "US" },
  { symbol: "CRWV", name: "CoreWeave", sector: "Technologie", region: "US" },
  { symbol: "NBIS", name: "Nebius Group", sector: "Technologie", region: "US" },
  { symbol: "TEM", name: "Tempus AI", sector: "Gesundheit", region: "US" },
  { symbol: "RKLB", name: "Rocket Lab", sector: "Industrie", region: "US" },
  { symbol: "ASTS", name: "AST SpaceMobile", sector: "Technologie", region: "US" },
  { symbol: "LUNR", name: "Intuitive Machines", sector: "Industrie", region: "US" },
  { symbol: "JOBY", name: "Joby Aviation", sector: "Industrie", region: "US" },
  { symbol: "ACHR", name: "Archer Aviation", sector: "Industrie", region: "US" },
  { symbol: "ANF", name: "Abercrombie & Fitch", sector: "Konsum", region: "US" },
  { symbol: "DKNG", name: "DraftKings", sector: "Konsum", region: "US" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Konsum", region: "US" },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Konsum", region: "US" },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Konsum", region: "US" },
  { symbol: "PARA", name: "Paramount Global", sector: "Konsum", region: "US" },
];

export const SECTORS = ["Technologie", "Energie", "Finanzen", "Gesundheit", "Konsum", "Industrie", "Rohstoffe"] as const;
export const INDICES = PRODUCTS.filter((p) => p.sector === "Index");
export const BENCHMARK = "SPY";

export function findProduct(symbol: string): Product | undefined {
  return PRODUCTS.find((p) => p.symbol.toUpperCase() === symbol.toUpperCase());
}

export function searchProducts(q: string): Product[] {
  const s = q.trim().toLowerCase();
  if (!s) return PRODUCTS;
  return PRODUCTS.filter((p) => p.symbol.toLowerCase().includes(s) || p.name.toLowerCase().includes(s));
}
