export type Product = {
  symbol: string;
  name: string;
  sector: "Technologie" | "Energie" | "Finanzen" | "Gesundheit" | "Konsum" | "Industrie" | "Rohstoffe" | "Index";
  region: "US" | "DE" | "EU" | "UK" | "JP";
  /** Marktkapitalisierungs-Klasse — wird beim Mergen aus der Source-Liste abgeleitet. */
  cap?: "large" | "mid" | "small";
};


import { PRODUCTS_EXTRA } from "./products-extra";
import { PRODUCTS_EXTRA2 } from "./products-extra2";

const PRODUCTS_BASE: Product[] = [
  // US Tech
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technologie", region: "US" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technologie", region: "US" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technologie", region: "US" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Technologie", region: "US" },
  { symbol: "META", name: "Meta Platforms", sector: "Technologie", region: "US" },
  { symbol: "AMZN", name: "Amazon", sector: "Konsum", region: "US" },
  { symbol: "TSLA", name: "Tesla", sector: "Konsum", region: "US" },
  { symbol: "AMD", name: "AMD", sector: "Technologie", region: "US" },
  { symbol: "INTC", name: "Intel", sector: "Technologie", region: "US" },
  { symbol: "ORCL", name: "Oracle", sector: "Technologie", region: "US" },
  { symbol: "CRM", name: "Salesforce", sector: "Technologie", region: "US" },
  { symbol: "NFLX", name: "Netflix", sector: "Konsum", region: "US" },
  // US Finanzen / Industrie / Energie / Gesundheit
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Finanzen", region: "US" },
  { symbol: "BAC", name: "Bank of America", sector: "Finanzen", region: "US" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Finanzen", region: "US" },
  { symbol: "V", name: "Visa", sector: "Finanzen", region: "US" },
  { symbol: "MA", name: "Mastercard", sector: "Finanzen", region: "US" },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energie", region: "US" },
  { symbol: "CVX", name: "Chevron", sector: "Energie", region: "US" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Gesundheit", region: "US" },
  { symbol: "PFE", name: "Pfizer", sector: "Gesundheit", region: "US" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Gesundheit", region: "US" },
  { symbol: "BA", name: "Boeing", sector: "Industrie", region: "US" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrie", region: "US" },
  { symbol: "KO", name: "Coca-Cola", sector: "Konsum", region: "US" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Konsum", region: "US" },
  // EU / DE
  { symbol: "SAP", name: "SAP SE", sector: "Technologie", region: "DE" },
  { symbol: "SIE.DE", name: "Siemens", sector: "Industrie", region: "DE" },
  { symbol: "DBK.DE", name: "Deutsche Bank", sector: "Finanzen", region: "DE" },
  { symbol: "VOW3.DE", name: "Volkswagen", sector: "Konsum", region: "DE" },
  { symbol: "BMW.DE", name: "BMW", sector: "Konsum", region: "DE" },
  { symbol: "BAYN.DE", name: "Bayer", sector: "Gesundheit", region: "DE" },
  { symbol: "AIR.PA", name: "Airbus", sector: "Industrie", region: "EU" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technologie", region: "EU" },
  { symbol: "ADBE", name: "Adobe", sector: "Technologie", region: "US" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technologie", region: "US" },
  { symbol: "CSCO", name: "Cisco", sector: "Technologie", region: "US" },
  { symbol: "IBM", name: "IBM", sector: "Technologie", region: "US" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technologie", region: "US" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technologie", region: "US" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technologie", region: "US" },
  { symbol: "INTU", name: "Intuit", sector: "Technologie", region: "US" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technologie", region: "US" },
  { symbol: "SNOW", name: "Snowflake", sector: "Technologie", region: "US" },
  { symbol: "SHOP", name: "Shopify", sector: "Technologie", region: "US" },
  { symbol: "UBER", name: "Uber", sector: "Technologie", region: "US" },
  { symbol: "PLTR", name: "Palantir", sector: "Technologie", region: "US" },
  { symbol: "PYPL", name: "PayPal", sector: "Finanzen", region: "US" },
  { symbol: "SQ", name: "Block", sector: "Finanzen", region: "US" },
  { symbol: "AXP", name: "American Express", sector: "Finanzen", region: "US" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Finanzen", region: "US" },
  { symbol: "C", name: "Citigroup", sector: "Finanzen", region: "US" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Finanzen", region: "US" },
  { symbol: "BLK", name: "BlackRock", sector: "Finanzen", region: "US" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Finanzen", region: "US" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Gesundheit", region: "US" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Gesundheit", region: "US" },
  { symbol: "ABBV", name: "AbbVie", sector: "Gesundheit", region: "US" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Gesundheit", region: "US" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Gesundheit", region: "US" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Gesundheit", region: "US" },
  { symbol: "DHR", name: "Danaher", sector: "Gesundheit", region: "US" },
  { symbol: "COST", name: "Costco", sector: "Konsum", region: "US" },
  { symbol: "WMT", name: "Walmart", sector: "Konsum", region: "US" },
  { symbol: "HD", name: "Home Depot", sector: "Konsum", region: "US" },
  { symbol: "MCD", name: "McDonald's", sector: "Konsum", region: "US" },
  { symbol: "NKE", name: "Nike", sector: "Konsum", region: "US" },
  { symbol: "DIS", name: "Disney", sector: "Konsum", region: "US" },
  { symbol: "SBUX", name: "Starbucks", sector: "Konsum", region: "US" },
  { symbol: "PEP", name: "PepsiCo", sector: "Konsum", region: "US" },
  { symbol: "TGT", name: "Target", sector: "Konsum", region: "US" },
  { symbol: "F", name: "Ford", sector: "Konsum", region: "US" },
  { symbol: "GM", name: "General Motors", sector: "Konsum", region: "US" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrie", region: "US" },
  { symbol: "HON", name: "Honeywell", sector: "Industrie", region: "US" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrie", region: "US" },
  { symbol: "RTX", name: "RTX", sector: "Industrie", region: "US" },
  { symbol: "UPS", name: "UPS", sector: "Industrie", region: "US" },
  { symbol: "DE", name: "Deere", sector: "Industrie", region: "US" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrie", region: "US" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Energie", region: "US" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energie", region: "US" },
  { symbol: "SLB", name: "Schlumberger", sector: "Energie", region: "US" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energie", region: "US" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Rohstoffe", region: "US" },
  { symbol: "NEM", name: "Newmont", sector: "Rohstoffe", region: "US" },
  { symbol: "LIN", name: "Linde", sector: "Rohstoffe", region: "US" },
  { symbol: "APD", name: "Air Products", sector: "Rohstoffe", region: "US" },
  { symbol: "ALV.DE", name: "Allianz", sector: "Finanzen", region: "DE" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", sector: "Technologie", region: "DE" },
  { symbol: "MUV2.DE", name: "Münchener Rück", sector: "Finanzen", region: "DE" },
  { symbol: "MBG.DE", name: "Mercedes-Benz", sector: "Konsum", region: "DE" },
  { symbol: "IFX.DE", name: "Infineon", sector: "Technologie", region: "DE" },
  { symbol: "BAS.DE", name: "BASF", sector: "Rohstoffe", region: "DE" },
  { symbol: "ADS.DE", name: "Adidas", sector: "Konsum", region: "DE" },
  { symbol: "RWE.DE", name: "RWE", sector: "Energie", region: "DE" },
  { symbol: "ENR.DE", name: "Siemens Energy", sector: "Energie", region: "DE" },
  { symbol: "CON.DE", name: "Continental", sector: "Konsum", region: "DE" },
  { symbol: "HEI.DE", name: "Heidelberg Materials", sector: "Rohstoffe", region: "DE" },
  { symbol: "DHL.DE", name: "DHL Group", sector: "Industrie", region: "DE" },
  { symbol: "EOAN.DE", name: "E.ON", sector: "Energie", region: "DE" },
  { symbol: "BNP.PA", name: "BNP Paribas", sector: "Finanzen", region: "EU" },
  { symbol: "OR.PA", name: "L'Oréal", sector: "Konsum", region: "EU" },
  { symbol: "MC.PA", name: "LVMH", sector: "Konsum", region: "EU" },
  { symbol: "SAN.PA", name: "Sanofi", sector: "Gesundheit", region: "EU" },
  { symbol: "SU.PA", name: "Schneider Electric", sector: "Industrie", region: "EU" },
  { symbol: "TTE.PA", name: "TotalEnergies", sector: "Energie", region: "EU" },
  { symbol: "RMS.PA", name: "Hermès", sector: "Konsum", region: "EU" },
  { symbol: "AI.PA", name: "Air Liquide", sector: "Rohstoffe", region: "EU" },
  { symbol: "SHEL", name: "Shell", sector: "Energie", region: "UK" },
  { symbol: "AZN", name: "AstraZeneca", sector: "Gesundheit", region: "UK" },
  { symbol: "NVO", name: "Novo Nordisk", sector: "Gesundheit", region: "EU" },
  { symbol: "UL", name: "Unilever", sector: "Konsum", region: "UK" },
  { symbol: "TM", name: "Toyota", sector: "Konsum", region: "JP" },
  { symbol: "SONY", name: "Sony", sector: "Technologie", region: "JP" },
  { symbol: "MUFG", name: "Mitsubishi UFJ", sector: "Finanzen", region: "JP" },
  { symbol: "HMC", name: "Honda", sector: "Konsum", region: "JP" },
  { symbol: "IXN", name: "Global Tech ETF", sector: "Index", region: "US" },
  { symbol: "IWM", name: "Russell 2000 (IWM)", sector: "Index", region: "US" },
  { symbol: "VTI", name: "US Gesamtmarkt (VTI)", sector: "Index", region: "US" },
  { symbol: "VEA", name: "Developed Markets (VEA)", sector: "Index", region: "EU" },
  { symbol: "EFA", name: "MSCI EAFE (EFA)", sector: "Index", region: "EU" },
  { symbol: "FEZ", name: "Euro Stoxx 50 (FEZ)", sector: "Index", region: "EU" },
  // Indizes (ETF-Proxys, da Finnhub Index-Tickers oft Premium sind)
  { symbol: "SPY", name: "S&P 500 (SPY)", sector: "Index", region: "US" },
  { symbol: "QQQ", name: "NASDAQ 100 (QQQ)", sector: "Index", region: "US" },
  { symbol: "DIA", name: "Dow Jones (DIA)", sector: "Index", region: "US" },
  { symbol: "EWG", name: "DAX-Proxy (EWG)", sector: "Index", region: "DE" },
  { symbol: "EWJ", name: "Nikkei-Proxy (EWJ)", sector: "Index", region: "JP" },

  // === Erweiterte US-Tech / Halbleiter ===
  { symbol: "MU", name: "Micron Technology", sector: "Technologie", region: "US" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technologie", region: "US" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technologie", region: "US" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technologie", region: "US" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Technologie", region: "US" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Technologie", region: "US" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Technologie", region: "US" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technologie", region: "US" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Technologie", region: "US" },
  { symbol: "TSM", name: "TSMC", sector: "Technologie", region: "US" },
  { symbol: "ARM", name: "Arm Holdings", sector: "Technologie", region: "US" },
  { symbol: "AMKR", name: "Amkor Technology", sector: "Technologie", region: "US" },
  { symbol: "WDC", name: "Western Digital", sector: "Technologie", region: "US" },
  { symbol: "STX", name: "Seagate Technology", sector: "Technologie", region: "US" },
  { symbol: "SMCI", name: "Super Micro Computer", sector: "Technologie", region: "US" },
  { symbol: "DELL", name: "Dell Technologies", sector: "Technologie", region: "US" },
  { symbol: "HPQ", name: "HP Inc.", sector: "Technologie", region: "US" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technologie", region: "US" },
  { symbol: "ANET", name: "Arista Networks", sector: "Technologie", region: "US" },

  // === Software / Cloud / Cybersecurity ===
  { symbol: "CRWD", name: "CrowdStrike", sector: "Technologie", region: "US" },
  { symbol: "ZS", name: "Zscaler", sector: "Technologie", region: "US" },
  { symbol: "NET", name: "Cloudflare", sector: "Technologie", region: "US" },
  { symbol: "DDOG", name: "Datadog", sector: "Technologie", region: "US" },
  { symbol: "MDB", name: "MongoDB", sector: "Technologie", region: "US" },
  { symbol: "TEAM", name: "Atlassian", sector: "Technologie", region: "US" },
  { symbol: "WDAY", name: "Workday", sector: "Technologie", region: "US" },
  { symbol: "PATH", name: "UiPath", sector: "Technologie", region: "US" },
  { symbol: "OKTA", name: "Okta", sector: "Technologie", region: "US" },
  { symbol: "FTNT", name: "Fortinet", sector: "Technologie", region: "US" },
  { symbol: "S", name: "SentinelOne", sector: "Technologie", region: "US" },
  { symbol: "U", name: "Unity Software", sector: "Technologie", region: "US" },
  { symbol: "DOCU", name: "DocuSign", sector: "Technologie", region: "US" },
  { symbol: "ZM", name: "Zoom Video", sector: "Technologie", region: "US" },
  { symbol: "TWLO", name: "Twilio", sector: "Technologie", region: "US" },
  { symbol: "ROKU", name: "Roku", sector: "Technologie", region: "US" },
  { symbol: "SPOT", name: "Spotify", sector: "Konsum", region: "US" },
  { symbol: "PINS", name: "Pinterest", sector: "Technologie", region: "US" },
  { symbol: "SNAP", name: "Snap Inc.", sector: "Technologie", region: "US" },
  { symbol: "RBLX", name: "Roblox", sector: "Technologie", region: "US" },
  { symbol: "ABNB", name: "Airbnb", sector: "Konsum", region: "US" },
  { symbol: "LYFT", name: "Lyft", sector: "Technologie", region: "US" },
  { symbol: "DASH", name: "DoorDash", sector: "Konsum", region: "US" },
  { symbol: "RDDT", name: "Reddit", sector: "Technologie", region: "US" },
  { symbol: "APP", name: "AppLovin", sector: "Technologie", region: "US" },

  // === EV / Mobility / Clean Energy ===
  { symbol: "RIVN", name: "Rivian", sector: "Konsum", region: "US" },
  { symbol: "LCID", name: "Lucid Group", sector: "Konsum", region: "US" },
  { symbol: "NIO", name: "NIO Inc.", sector: "Konsum", region: "US" },
  { symbol: "XPEV", name: "XPeng", sector: "Konsum", region: "US" },
  { symbol: "LI", name: "Li Auto", sector: "Konsum", region: "US" },
  { symbol: "BYDDY", name: "BYD Company", sector: "Konsum", region: "US" },
  { symbol: "ENPH", name: "Enphase Energy", sector: "Energie", region: "US" },
  { symbol: "SEDG", name: "SolarEdge", sector: "Energie", region: "US" },
  { symbol: "FSLR", name: "First Solar", sector: "Energie", region: "US" },
  { symbol: "PLUG", name: "Plug Power", sector: "Energie", region: "US" },

  // === Biotech / Pharma ===
  { symbol: "MRNA", name: "Moderna", sector: "Gesundheit", region: "US" },
  { symbol: "BNTX", name: "BioNTech", sector: "Gesundheit", region: "EU" },
  { symbol: "REGN", name: "Regeneron", sector: "Gesundheit", region: "US" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Gesundheit", region: "US" },
  { symbol: "AMGN", name: "Amgen", sector: "Gesundheit", region: "US" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Gesundheit", region: "US" },
  { symbol: "CVS", name: "CVS Health", sector: "Gesundheit", region: "US" },
  { symbol: "NVAX", name: "Novavax", sector: "Gesundheit", region: "US" },

  // === China / Asien ADRs ===
  { symbol: "BABA", name: "Alibaba", sector: "Konsum", region: "JP" },
  { symbol: "JD", name: "JD.com", sector: "Konsum", region: "JP" },
  { symbol: "PDD", name: "PDD Holdings", sector: "Konsum", region: "JP" },
  { symbol: "BIDU", name: "Baidu", sector: "Technologie", region: "JP" },
  { symbol: "TCEHY", name: "Tencent", sector: "Technologie", region: "JP" },

  // === Crypto-Proxys ===
  { symbol: "COIN", name: "Coinbase", sector: "Finanzen", region: "US" },
  { symbol: "MSTR", name: "MicroStrategy", sector: "Technologie", region: "US" },
  { symbol: "MARA", name: "Marathon Digital", sector: "Technologie", region: "US" },
  { symbol: "RIOT", name: "Riot Platforms", sector: "Technologie", region: "US" },
  { symbol: "HOOD", name: "Robinhood Markets", sector: "Finanzen", region: "US" },

  // === Finanzen erweitert ===
  { symbol: "SCHW", name: "Charles Schwab", sector: "Finanzen", region: "US" },
  { symbol: "SPGI", name: "S&P Global", sector: "Finanzen", region: "US" },
  { symbol: "MCO", name: "Moody's", sector: "Finanzen", region: "US" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Finanzen", region: "US" },
  { symbol: "CME", name: "CME Group", sector: "Finanzen", region: "US" },

  // === EU / DE erweitert ===
  { symbol: "RHM.DE", name: "Rheinmetall", sector: "Industrie", region: "DE" },
  { symbol: "HEN3.DE", name: "Henkel", sector: "Konsum", region: "DE" },
  { symbol: "FRE.DE", name: "Fresenius", sector: "Gesundheit", region: "DE" },
  { symbol: "DPW.DE", name: "Deutsche Post", sector: "Industrie", region: "DE" },
  { symbol: "PAH3.DE", name: "Porsche Automobil Holding", sector: "Konsum", region: "DE" },
  { symbol: "P911.DE", name: "Porsche AG", sector: "Konsum", region: "DE" },
  { symbol: "ZAL.DE", name: "Zalando", sector: "Konsum", region: "DE" },
  { symbol: "SHL.DE", name: "Siemens Healthineers", sector: "Gesundheit", region: "DE" },
  { symbol: "MTX.DE", name: "MTU Aero Engines", sector: "Industrie", region: "DE" },
  { symbol: "ENGI.PA", name: "Engie", sector: "Energie", region: "EU" },
  { symbol: "BN.PA", name: "Danone", sector: "Konsum", region: "EU" },
  { symbol: "CAP.PA", name: "Capgemini", sector: "Technologie", region: "EU" },
  { symbol: "NESN.SW", name: "Nestlé", sector: "Konsum", region: "EU" },
  { symbol: "ROG.SW", name: "Roche", sector: "Gesundheit", region: "EU" },
  { symbol: "NOVN.SW", name: "Novartis", sector: "Gesundheit", region: "EU" },
  { symbol: "UBSG.SW", name: "UBS Group", sector: "Finanzen", region: "EU" },

  // === Sektor- & Themen-ETFs ===
  { symbol: "SMH", name: "Semiconductor ETF (SMH)", sector: "Index", region: "US" },
  { symbol: "SOXX", name: "iShares Semiconductor (SOXX)", sector: "Index", region: "US" },
  { symbol: "XLK", name: "Technology Select (XLK)", sector: "Index", region: "US" },
  { symbol: "XLF", name: "Financial Select (XLF)", sector: "Index", region: "US" },
  { symbol: "XLE", name: "Energy Select (XLE)", sector: "Index", region: "US" },
  { symbol: "XLV", name: "Health Care Select (XLV)", sector: "Index", region: "US" },
  { symbol: "XLY", name: "Consumer Discretionary (XLY)", sector: "Index", region: "US" },
  { symbol: "XLP", name: "Consumer Staples (XLP)", sector: "Index", region: "US" },
  { symbol: "XLI", name: "Industrials Select (XLI)", sector: "Index", region: "US" },
  { symbol: "XLU", name: "Utilities Select (XLU)", sector: "Index", region: "US" },
  { symbol: "XLB", name: "Materials Select (XLB)", sector: "Index", region: "US" },
  { symbol: "XLRE", name: "Real Estate Select (XLRE)", sector: "Index", region: "US" },
  { symbol: "XLC", name: "Communication Services (XLC)", sector: "Index", region: "US" },
  { symbol: "ARKK", name: "ARK Innovation (ARKK)", sector: "Index", region: "US" },
  { symbol: "ARKG", name: "ARK Genomic (ARKG)", sector: "Index", region: "US" },
  { symbol: "ARKW", name: "ARK Next Gen Internet", sector: "Index", region: "US" },
  { symbol: "TAN", name: "Solar ETF (TAN)", sector: "Index", region: "US" },
  { symbol: "ICLN", name: "Clean Energy (ICLN)", sector: "Index", region: "US" },
  { symbol: "LIT", name: "Lithium & Battery (LIT)", sector: "Index", region: "US" },
  { symbol: "URA", name: "Uranium ETF (URA)", sector: "Index", region: "US" },
  { symbol: "JETS", name: "Airline ETF (JETS)", sector: "Index", region: "US" },
  { symbol: "IBB", name: "Biotech ETF (IBB)", sector: "Index", region: "US" },
  { symbol: "XBI", name: "S&P Biotech (XBI)", sector: "Index", region: "US" },
  { symbol: "KWEB", name: "China Internet (KWEB)", sector: "Index", region: "US" },
  { symbol: "FXI", name: "China Large-Cap (FXI)", sector: "Index", region: "US" },
  { symbol: "MCHI", name: "MSCI China (MCHI)", sector: "Index", region: "US" },
  { symbol: "EEM", name: "Emerging Markets (EEM)", sector: "Index", region: "US" },
  { symbol: "VWO", name: "Vanguard Emerging (VWO)", sector: "Index", region: "US" },
  { symbol: "INDA", name: "MSCI India (INDA)", sector: "Index", region: "JP" },
  { symbol: "EWZ", name: "MSCI Brazil (EWZ)", sector: "Index", region: "US" },
  { symbol: "EWU", name: "MSCI UK (EWU)", sector: "Index", region: "UK" },

  // === Rohstoff- & Anleihen-ETFs ===
  { symbol: "GLD", name: "Gold ETF (GLD)", sector: "Index", region: "US" },
  { symbol: "IAU", name: "iShares Gold (IAU)", sector: "Index", region: "US" },
  { symbol: "SLV", name: "Silber ETF (SLV)", sector: "Index", region: "US" },
  { symbol: "USO", name: "Oil Fund (USO)", sector: "Index", region: "US" },
  { symbol: "UNG", name: "Natural Gas (UNG)", sector: "Index", region: "US" },
  { symbol: "DBC", name: "Commodity Index (DBC)", sector: "Index", region: "US" },
  { symbol: "TLT", name: "20+ Year Treasury (TLT)", sector: "Index", region: "US" },
  { symbol: "IEF", name: "7-10Y Treasury (IEF)", sector: "Index", region: "US" },
  { symbol: "SHY", name: "1-3Y Treasury (SHY)", sector: "Index", region: "US" },
  { symbol: "HYG", name: "High Yield Corp (HYG)", sector: "Index", region: "US" },
  { symbol: "LQD", name: "Investment Grade (LQD)", sector: "Index", region: "US" },
  { symbol: "BITO", name: "Bitcoin Strategy ETF", sector: "Index", region: "US" },
  { symbol: "IBIT", name: "iShares Bitcoin Trust", sector: "Index", region: "US" },
  { symbol: "ETHE", name: "Grayscale Ethereum", sector: "Index", region: "US" },

  // === Volatilität ===
  { symbol: "VIXY", name: "VIX Short-Term (VIXY)", sector: "Index", region: "US" },
  { symbol: "UVXY", name: "Ultra VIX (UVXY)", sector: "Index", region: "US" },

  // === Weitere US Large Caps / Konsum / Telekom ===
  { symbol: "T", name: "AT&T", sector: "Technologie", region: "US" },
  { symbol: "VZ", name: "Verizon", sector: "Technologie", region: "US" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Technologie", region: "US" },
  { symbol: "CMCSA", name: "Comcast", sector: "Konsum", region: "US" },
  { symbol: "PM", name: "Philip Morris", sector: "Konsum", region: "US" },
  { symbol: "MO", name: "Altria", sector: "Konsum", region: "US" },
  { symbol: "MDLZ", name: "Mondelez", sector: "Konsum", region: "US" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Konsum", region: "US" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Konsum", region: "US" },
  { symbol: "GIS", name: "General Mills", sector: "Konsum", region: "US" },
  { symbol: "HSY", name: "Hershey", sector: "Konsum", region: "US" },
  { symbol: "EL", name: "Estée Lauder", sector: "Konsum", region: "US" },
  { symbol: "LOW", name: "Lowe's", sector: "Konsum", region: "US" },
  { symbol: "TJX", name: "TJX Companies", sector: "Konsum", region: "US" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Konsum", region: "US" },
  { symbol: "MAR", name: "Marriott", sector: "Konsum", region: "US" },
  { symbol: "HLT", name: "Hilton", sector: "Konsum", region: "US" },
  { symbol: "CMG", name: "Chipotle", sector: "Konsum", region: "US" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Konsum", region: "US" },
  { symbol: "EBAY", name: "eBay", sector: "Konsum", region: "US" },
  { symbol: "ETSY", name: "Etsy", sector: "Konsum", region: "US" },
  { symbol: "CHWY", name: "Chewy", sector: "Konsum", region: "US" },

  // === Industrie & Transport ===
  { symbol: "FDX", name: "FedEx", sector: "Industrie", region: "US" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrie", region: "US" },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrie", region: "US" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrie", region: "US" },
  { symbol: "UAL", name: "United Airlines", sector: "Industrie", region: "US" },
  { symbol: "AAL", name: "American Airlines", sector: "Industrie", region: "US" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrie", region: "US" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrie", region: "US" },
  { symbol: "ETN", name: "Eaton", sector: "Industrie", region: "US" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrie", region: "US" },
  { symbol: "PH", name: "Parker Hannifin", sector: "Industrie", region: "US" },
  { symbol: "MMM", name: "3M", sector: "Industrie", region: "US" },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrie", region: "US" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrie", region: "US" },
  { symbol: "TDG", name: "TransDigm Group", sector: "Industrie", region: "US" },

  // === Energie & Versorger ===
  { symbol: "PSX", name: "Phillips 66", sector: "Energie", region: "US" },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energie", region: "US" },
  { symbol: "VLO", name: "Valero Energy", sector: "Energie", region: "US" },
  { symbol: "EOG", name: "EOG Resources", sector: "Energie", region: "US" },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energie", region: "US" },
  { symbol: "WMB", name: "Williams Companies", sector: "Energie", region: "US" },
  { symbol: "DUK", name: "Duke Energy", sector: "Energie", region: "US" },
  { symbol: "SO", name: "Southern Company", sector: "Energie", region: "US" },
  { symbol: "AEP", name: "American Electric Power", sector: "Energie", region: "US" },
  { symbol: "EXC", name: "Exelon", sector: "Energie", region: "US" },

  // === Rohstoffe / Materials ===
  { symbol: "DOW", name: "Dow Inc.", sector: "Rohstoffe", region: "US" },
  { symbol: "DD", name: "DuPont", sector: "Rohstoffe", region: "US" },
  { symbol: "PPG", name: "PPG Industries", sector: "Rohstoffe", region: "US" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Rohstoffe", region: "US" },
  { symbol: "ECL", name: "Ecolab", sector: "Rohstoffe", region: "US" },
  { symbol: "NUE", name: "Nucor", sector: "Rohstoffe", region: "US" },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Rohstoffe", region: "US" },
  { symbol: "CLF", name: "Cleveland-Cliffs", sector: "Rohstoffe", region: "US" },
  { symbol: "AA", name: "Alcoa", sector: "Rohstoffe", region: "US" },
  { symbol: "GOLD", name: "Barrick Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "AEM", name: "Agnico Eagle Mines", sector: "Rohstoffe", region: "US" },
  { symbol: "MOS", name: "Mosaic", sector: "Rohstoffe", region: "US" },
  { symbol: "CF", name: "CF Industries", sector: "Rohstoffe", region: "US" },

  // === Gesundheit erweitert ===
  { symbol: "ELV", name: "Elevance Health", sector: "Gesundheit", region: "US" },
  { symbol: "CI", name: "Cigna", sector: "Gesundheit", region: "US" },
  { symbol: "HUM", name: "Humana", sector: "Gesundheit", region: "US" },
  { symbol: "MDT", name: "Medtronic", sector: "Gesundheit", region: "US" },
  { symbol: "SYK", name: "Stryker", sector: "Gesundheit", region: "US" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Gesundheit", region: "US" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Gesundheit", region: "US" },
  { symbol: "ZBH", name: "Zimmer Biomet", sector: "Gesundheit", region: "US" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Gesundheit", region: "US" },
  { symbol: "IDXX", name: "IDEXX Laboratories", sector: "Gesundheit", region: "US" },
  { symbol: "BIIB", name: "Biogen", sector: "Gesundheit", region: "US" },
  { symbol: "ILMN", name: "Illumina", sector: "Gesundheit", region: "US" },

  // === Finanzen erweitert ===
  { symbol: "USB", name: "U.S. Bancorp", sector: "Finanzen", region: "US" },
  { symbol: "PNC", name: "PNC Financial", sector: "Finanzen", region: "US" },
  { symbol: "TFC", name: "Truist Financial", sector: "Finanzen", region: "US" },
  { symbol: "COF", name: "Capital One", sector: "Finanzen", region: "US" },
  { symbol: "DFS", name: "Discover Financial", sector: "Finanzen", region: "US" },
  { symbol: "MET", name: "MetLife", sector: "Finanzen", region: "US" },
  { symbol: "PRU", name: "Prudential Financial", sector: "Finanzen", region: "US" },
  { symbol: "AIG", name: "AIG", sector: "Finanzen", region: "US" },
  { symbol: "ALL", name: "Allstate", sector: "Finanzen", region: "US" },
  { symbol: "TRV", name: "Travelers", sector: "Finanzen", region: "US" },
  { symbol: "CB", name: "Chubb", sector: "Finanzen", region: "US" },
  { symbol: "AON", name: "Aon", sector: "Finanzen", region: "US" },
  { symbol: "MMC", name: "Marsh McLennan", sector: "Finanzen", region: "US" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", sector: "Finanzen", region: "US" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Finanzen", region: "US" },

  // === REITs ===
  { symbol: "PLD", name: "Prologis", sector: "Finanzen", region: "US" },
  { symbol: "AMT", name: "American Tower", sector: "Finanzen", region: "US" },
  { symbol: "EQIX", name: "Equinix", sector: "Finanzen", region: "US" },
  { symbol: "CCI", name: "Crown Castle", sector: "Finanzen", region: "US" },
  { symbol: "O", name: "Realty Income", sector: "Finanzen", region: "US" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Finanzen", region: "US" },
  { symbol: "PSA", name: "Public Storage", sector: "Finanzen", region: "US" },

  // === EU/UK erweitert ===
  { symbol: "VNA.DE", name: "Vonovia", sector: "Finanzen", region: "DE" },
  { symbol: "BEI.DE", name: "Beiersdorf", sector: "Konsum", region: "DE" },
  { symbol: "SRT3.DE", name: "Sartorius", sector: "Gesundheit", region: "DE" },
  { symbol: "QIA.DE", name: "Qiagen", sector: "Gesundheit", region: "DE" },
  { symbol: "PUM.DE", name: "Puma", sector: "Konsum", region: "DE" },
  { symbol: "HFG.DE", name: "HelloFresh", sector: "Konsum", region: "DE" },
  { symbol: "DB1.DE", name: "Deutsche Börse", sector: "Finanzen", region: "DE" },
  { symbol: "CBK.DE", name: "Commerzbank", sector: "Finanzen", region: "DE" },
  { symbol: "LHA.DE", name: "Lufthansa", sector: "Industrie", region: "DE" },
  { symbol: "SY1.DE", name: "Symrise", sector: "Rohstoffe", region: "DE" },
  { symbol: "ACA.PA", name: "Crédit Agricole", sector: "Finanzen", region: "EU" },
  { symbol: "GLE.PA", name: "Société Générale", sector: "Finanzen", region: "EU" },
  { symbol: "KER.PA", name: "Kering", sector: "Konsum", region: "EU" },
  { symbol: "SAF.PA", name: "Safran", sector: "Industrie", region: "EU" },
  { symbol: "DG.PA", name: "Vinci", sector: "Industrie", region: "EU" },
  { symbol: "ABBN.SW", name: "ABB", sector: "Industrie", region: "EU" },
  { symbol: "ZURN.SW", name: "Zurich Insurance", sector: "Finanzen", region: "EU" },
  { symbol: "GIVN.SW", name: "Givaudan", sector: "Rohstoffe", region: "EU" },
  { symbol: "HSBC", name: "HSBC Holdings", sector: "Finanzen", region: "UK" },
  { symbol: "BP", name: "BP plc", sector: "Energie", region: "UK" },
  { symbol: "RIO", name: "Rio Tinto", sector: "Rohstoffe", region: "UK" },
  { symbol: "BHP", name: "BHP Group", sector: "Rohstoffe", region: "UK" },
  { symbol: "GSK", name: "GSK plc", sector: "Gesundheit", region: "UK" },
  { symbol: "DEO", name: "Diageo", sector: "Konsum", region: "UK" },
  { symbol: "BTI", name: "British American Tobacco", sector: "Konsum", region: "UK" },
  { symbol: "STLA", name: "Stellantis", sector: "Konsum", region: "EU" },
  { symbol: "ENEL.MI", name: "Enel", sector: "Energie", region: "EU" },
  { symbol: "ENI.MI", name: "Eni", sector: "Energie", region: "EU" },
  { symbol: "ISP.MI", name: "Intesa Sanpaolo", sector: "Finanzen", region: "EU" },
  { symbol: "UCG.MI", name: "UniCredit", sector: "Finanzen", region: "EU" },
  { symbol: "RACE", name: "Ferrari", sector: "Konsum", region: "EU" },
  { symbol: "IBE.MC", name: "Iberdrola", sector: "Energie", region: "EU" },
  { symbol: "ITX.MC", name: "Inditex", sector: "Konsum", region: "EU" },

  // === Asien erweitert ===
  { symbol: "7203.T", name: "Toyota Motor (Tokio)", sector: "Konsum", region: "JP" },
  { symbol: "6758.T", name: "Sony Group (Tokio)", sector: "Technologie", region: "JP" },
  { symbol: "9984.T", name: "SoftBank Group", sector: "Technologie", region: "JP" },
  { symbol: "6861.T", name: "Keyence", sector: "Industrie", region: "JP" },
  { symbol: "7974.T", name: "Nintendo", sector: "Technologie", region: "JP" },
  { symbol: "NTES", name: "NetEase", sector: "Technologie", region: "JP" },
  { symbol: "TCOM", name: "Trip.com Group", sector: "Konsum", region: "JP" },
  { symbol: "BILI", name: "Bilibili", sector: "Technologie", region: "JP" },
  { symbol: "INFY", name: "Infosys", sector: "Technologie", region: "JP" },
  { symbol: "WIT", name: "Wipro", sector: "Technologie", region: "JP" },

  // === Mehr ETFs (Regional / Faktor / Income) ===
  { symbol: "VOO", name: "Vanguard S&P 500 (VOO)", sector: "Index", region: "US" },
  { symbol: "IVV", name: "iShares Core S&P 500 (IVV)", sector: "Index", region: "US" },
  { symbol: "SCHD", name: "Schwab US Dividend (SCHD)", sector: "Index", region: "US" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation", sector: "Index", region: "US" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield", sector: "Index", region: "US" },
  { symbol: "DVY", name: "iShares Select Dividend (DVY)", sector: "Index", region: "US" },
  { symbol: "JEPI", name: "JPMorgan Equity Premium (JEPI)", sector: "Index", region: "US" },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Premium (JEPQ)", sector: "Index", region: "US" },
  { symbol: "MOAT", name: "VanEck Moat (MOAT)", sector: "Index", region: "US" },
  { symbol: "MTUM", name: "iShares Momentum (MTUM)", sector: "Index", region: "US" },
  { symbol: "QUAL", name: "iShares Quality (QUAL)", sector: "Index", region: "US" },
  { symbol: "USMV", name: "iShares Min Vol (USMV)", sector: "Index", region: "US" },
  { symbol: "VTV", name: "Vanguard Value (VTV)", sector: "Index", region: "US" },
  { symbol: "VUG", name: "Vanguard Growth (VUG)", sector: "Index", region: "US" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth", sector: "Index", region: "US" },
  { symbol: "IWD", name: "iShares Russell 1000 Value", sector: "Index", region: "US" },
  { symbol: "IJH", name: "iShares Core S&P MidCap (IJH)", sector: "Index", region: "US" },
  { symbol: "IJR", name: "iShares Core S&P SmallCap (IJR)", sector: "Index", region: "US" },
  { symbol: "VXUS", name: "Vanguard Total Intl Stock", sector: "Index", region: "EU" },
  { symbol: "ACWI", name: "MSCI ACWI (ACWI)", sector: "Index", region: "US" },
  { symbol: "EZU", name: "MSCI Eurozone (EZU)", sector: "Index", region: "EU" },
  { symbol: "EWQ", name: "MSCI France (EWQ)", sector: "Index", region: "EU" },
  { symbol: "EWI", name: "MSCI Italy (EWI)", sector: "Index", region: "EU" },
  { symbol: "EWP", name: "MSCI Spain (EWP)", sector: "Index", region: "EU" },
  { symbol: "EWL", name: "MSCI Switzerland (EWL)", sector: "Index", region: "EU" },
  { symbol: "EWN", name: "MSCI Netherlands (EWN)", sector: "Index", region: "EU" },
  { symbol: "EWA", name: "MSCI Australia (EWA)", sector: "Index", region: "JP" },
  { symbol: "EWC", name: "MSCI Canada (EWC)", sector: "Index", region: "US" },
  { symbol: "EWT", name: "MSCI Taiwan (EWT)", sector: "Index", region: "JP" },
  { symbol: "EWY", name: "MSCI South Korea (EWY)", sector: "Index", region: "JP" },
  { symbol: "EWS", name: "MSCI Singapore (EWS)", sector: "Index", region: "JP" },
  { symbol: "EWH", name: "MSCI Hong Kong (EWH)", sector: "Index", region: "JP" },
  { symbol: "EWW", name: "MSCI Mexico (EWW)", sector: "Index", region: "US" },

  // === Themen-ETFs erweitert ===
  { symbol: "BOTZ", name: "Robotics & AI (BOTZ)", sector: "Index", region: "US" },
  { symbol: "ROBO", name: "Robotics ETF (ROBO)", sector: "Index", region: "US" },
  { symbol: "AIQ", name: "AI & Tech ETF (AIQ)", sector: "Index", region: "US" },
  { symbol: "CIBR", name: "Cybersecurity ETF (CIBR)", sector: "Index", region: "US" },
  { symbol: "HACK", name: "Cyber Security (HACK)", sector: "Index", region: "US" },
  { symbol: "FINX", name: "FinTech ETF (FINX)", sector: "Index", region: "US" },
  { symbol: "BLOK", name: "Blockchain ETF (BLOK)", sector: "Index", region: "US" },
  { symbol: "GAMR", name: "Video Games (GAMR)", sector: "Index", region: "US" },
  { symbol: "HERO", name: "Esports ETF (HERO)", sector: "Index", region: "US" },
  { symbol: "DRIV", name: "Autonomous EV (DRIV)", sector: "Index", region: "US" },
  { symbol: "ITA", name: "Aerospace & Defense (ITA)", sector: "Index", region: "US" },
  { symbol: "KRE", name: "Regional Banks (KRE)", sector: "Index", region: "US" },
  { symbol: "KBE", name: "S&P Bank (KBE)", sector: "Index", region: "US" },
  { symbol: "VNQ", name: "Vanguard Real Estate (VNQ)", sector: "Index", region: "US" },
  { symbol: "GDX", name: "Gold Miners (GDX)", sector: "Index", region: "US" },
  { symbol: "GDXJ", name: "Junior Gold Miners (GDXJ)", sector: "Index", region: "US" },
  { symbol: "COPX", name: "Copper Miners (COPX)", sector: "Index", region: "US" },
  { symbol: "REMX", name: "Rare Earth Metals (REMX)", sector: "Index", region: "US" },
  { symbol: "WEAT", name: "Wheat Fund (WEAT)", sector: "Index", region: "US" },
  { symbol: "CORN", name: "Corn Fund (CORN)", sector: "Index", region: "US" },

  // === Bond / Income erweitert ===
  { symbol: "AGG", name: "iShares Core US Aggregate", sector: "Index", region: "US" },
  { symbol: "BND", name: "Vanguard Total Bond (BND)", sector: "Index", region: "US" },
  { symbol: "BNDX", name: "Vanguard Total Intl Bond", sector: "Index", region: "EU" },
  { symbol: "TIP", name: "TIPS Bond ETF (TIP)", sector: "Index", region: "US" },
  { symbol: "MUB", name: "Municipal Bond (MUB)", sector: "Index", region: "US" },
  { symbol: "EMB", name: "Emerging Markets Bond", sector: "Index", region: "US" },

  // === Krypto-bezogen erweitert ===
  { symbol: "FBTC", name: "Fidelity Wise Origin Bitcoin", sector: "Index", region: "US" },
  { symbol: "ARKB", name: "ARK 21Shares Bitcoin", sector: "Index", region: "US" },
  { symbol: "ETHA", name: "iShares Ethereum Trust", sector: "Index", region: "US" },
  { symbol: "BTBT", name: "Bit Digital", sector: "Technologie", region: "US" },
  { symbol: "CIFR", name: "Cipher Mining", sector: "Technologie", region: "US" },
  { symbol: "CLSK", name: "CleanSpark", sector: "Technologie", region: "US" },

  // === Häufig gesuchte Nachzügler ===
  { symbol: "VRT", name: "Vertiv Holdings", sector: "Industrie", region: "US" },
  { symbol: "VST", name: "Vistra Corp", sector: "Energie", region: "US" },
  { symbol: "CEG", name: "Constellation Energy", sector: "Energie", region: "US" },
  { symbol: "TLN", name: "Talen Energy", sector: "Energie", region: "US" },
  { symbol: "OKLO", name: "Oklo Inc.", sector: "Energie", region: "US" },
  { symbol: "SMR", name: "NuScale Power", sector: "Energie", region: "US" },
  { symbol: "CRWV", name: "CoreWeave", sector: "Technologie", region: "US" },
  { symbol: "NBIS", name: "Nebius Group", sector: "Technologie", region: "US" },
  { symbol: "TEM", name: "Tempus AI", sector: "Gesundheit", region: "US" },
  { symbol: "RKLB", name: "Rocket Lab", sector: "Industrie", region: "US" },
  { symbol: "ASTS", name: "AST SpaceMobile", sector: "Technologie", region: "US" },
  { symbol: "LUNR", name: "Intuitive Machines", sector: "Industrie", region: "US" },
  { symbol: "JOBY", name: "Joby Aviation", sector: "Industrie", region: "US" },
  { symbol: "ACHR", name: "Archer Aviation", sector: "Industrie", region: "US" },
  { symbol: "ANF", name: "Abercrombie & Fitch", sector: "Konsum", region: "US" },
  { symbol: "DKNG", name: "DraftKings", sector: "Konsum", region: "US" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Konsum", region: "US" },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Konsum", region: "US" },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Konsum", region: "US" },
  { symbol: "PARA", name: "Paramount Global", sector: "Konsum", region: "US" },

  // === FTSE 100 (London) ===
  { symbol: "SHEL.L", name: "Shell plc (London)", sector: "Energie", region: "UK" },
  { symbol: "AZN.L", name: "AstraZeneca (London)", sector: "Gesundheit", region: "UK" },
  { symbol: "HSBA.L", name: "HSBC Holdings (London)", sector: "Finanzen", region: "UK" },
  { symbol: "ULVR.L", name: "Unilever (London)", sector: "Konsum", region: "UK" },
  { symbol: "BP.L", name: "BP (London)", sector: "Energie", region: "UK" },
  { symbol: "GSK.L", name: "GSK plc (London)", sector: "Gesundheit", region: "UK" },
  { symbol: "RIO.L", name: "Rio Tinto (London)", sector: "Rohstoffe", region: "UK" },
  { symbol: "DGE.L", name: "Diageo", sector: "Konsum", region: "UK" },
  { symbol: "BATS.L", name: "British American Tobacco", sector: "Konsum", region: "UK" },
  { symbol: "GLEN.L", name: "Glencore", sector: "Rohstoffe", region: "UK" },
  { symbol: "BARC.L", name: "Barclays", sector: "Finanzen", region: "UK" },
  { symbol: "LLOY.L", name: "Lloyds Banking Group", sector: "Finanzen", region: "UK" },
  { symbol: "NWG.L", name: "NatWest Group", sector: "Finanzen", region: "UK" },
  { symbol: "STAN.L", name: "Standard Chartered", sector: "Finanzen", region: "UK" },
  { symbol: "PRU.L", name: "Prudential plc", sector: "Finanzen", region: "UK" },
  { symbol: "LGEN.L", name: "Legal & General", sector: "Finanzen", region: "UK" },
  { symbol: "AAL.L", name: "Anglo American", sector: "Rohstoffe", region: "UK" },
  { symbol: "AHT.L", name: "Ashtead Group", sector: "Industrie", region: "UK" },
  { symbol: "BA.L", name: "BAE Systems", sector: "Industrie", region: "UK" },
  { symbol: "RR.L", name: "Rolls-Royce Holdings", sector: "Industrie", region: "UK" },
  { symbol: "EXPN.L", name: "Experian", sector: "Technologie", region: "UK" },
  { symbol: "REL.L", name: "RELX", sector: "Technologie", region: "UK" },
  { symbol: "VOD.L", name: "Vodafone Group", sector: "Technologie", region: "UK" },
  { symbol: "BT-A.L", name: "BT Group", sector: "Technologie", region: "UK" },
  { symbol: "TSCO.L", name: "Tesco", sector: "Konsum", region: "UK" },
  { symbol: "SBRY.L", name: "Sainsbury's", sector: "Konsum", region: "UK" },
  { symbol: "NG.L", name: "National Grid", sector: "Energie", region: "UK" },
  { symbol: "SSE.L", name: "SSE plc", sector: "Energie", region: "UK" },
  { symbol: "CRH", name: "CRH plc", sector: "Rohstoffe", region: "UK" },
  { symbol: "FLTR.L", name: "Flutter Entertainment", sector: "Konsum", region: "UK" },
  { symbol: "IMB.L", name: "Imperial Brands", sector: "Konsum", region: "UK" },

  // === CAC 40 (Paris) erweitert ===
  { symbol: "CS.PA", name: "AXA", sector: "Finanzen", region: "EU" },
  { symbol: "DSY.PA", name: "Dassault Systèmes", sector: "Technologie", region: "EU" },
  { symbol: "EL.PA", name: "EssilorLuxottica", sector: "Gesundheit", region: "EU" },
  { symbol: "PUB.PA", name: "Publicis Groupe", sector: "Konsum", region: "EU" },
  { symbol: "RI.PA", name: "Pernod Ricard", sector: "Konsum", region: "EU" },
  { symbol: "ML.PA", name: "Michelin", sector: "Konsum", region: "EU" },
  { symbol: "STM.PA", name: "STMicroelectronics", sector: "Technologie", region: "EU" },
  { symbol: "URW.PA", name: "Unibail-Rodamco-Westfield", sector: "Finanzen", region: "EU" },
  { symbol: "VIE.PA", name: "Veolia Environnement", sector: "Energie", region: "EU" },
  { symbol: "CA.PA", name: "Carrefour", sector: "Konsum", region: "EU" },
  { symbol: "ATO.PA", name: "Atos", sector: "Technologie", region: "EU" },
  { symbol: "EN.PA", name: "Bouygues", sector: "Industrie", region: "EU" },
  { symbol: "LR.PA", name: "Legrand", sector: "Industrie", region: "EU" },
  { symbol: "HO.PA", name: "Thales", sector: "Industrie", region: "EU" },
  { symbol: "ORA.PA", name: "Orange", sector: "Technologie", region: "EU" },

  // === Nikkei 225 / Japan erweitert (Tokio) ===
  { symbol: "6501.T", name: "Hitachi", sector: "Industrie", region: "JP" },
  { symbol: "6594.T", name: "Nidec", sector: "Industrie", region: "JP" },
  { symbol: "6902.T", name: "Denso", sector: "Industrie", region: "JP" },
  { symbol: "6954.T", name: "Fanuc", sector: "Industrie", region: "JP" },
  { symbol: "6981.T", name: "Murata Manufacturing", sector: "Technologie", region: "JP" },
  { symbol: "7267.T", name: "Honda Motor (Tokio)", sector: "Konsum", region: "JP" },
  { symbol: "7201.T", name: "Nissan Motor", sector: "Konsum", region: "JP" },
  { symbol: "7269.T", name: "Suzuki Motor", sector: "Konsum", region: "JP" },
  { symbol: "7270.T", name: "Subaru", sector: "Konsum", region: "JP" },
  { symbol: "7751.T", name: "Canon", sector: "Technologie", region: "JP" },
  { symbol: "8035.T", name: "Tokyo Electron", sector: "Technologie", region: "JP" },
  { symbol: "8058.T", name: "Mitsubishi Corporation", sector: "Industrie", region: "JP" },
  { symbol: "8031.T", name: "Mitsui & Co.", sector: "Industrie", region: "JP" },
  { symbol: "8001.T", name: "Itochu", sector: "Industrie", region: "JP" },
  { symbol: "8316.T", name: "Sumitomo Mitsui Financial", sector: "Finanzen", region: "JP" },
  { symbol: "8411.T", name: "Mizuho Financial", sector: "Finanzen", region: "JP" },
  { symbol: "8306.T", name: "Mitsubishi UFJ (Tokio)", sector: "Finanzen", region: "JP" },
  { symbol: "9432.T", name: "NTT", sector: "Technologie", region: "JP" },
  { symbol: "9433.T", name: "KDDI", sector: "Technologie", region: "JP" },
  { symbol: "9434.T", name: "SoftBank Corp.", sector: "Technologie", region: "JP" },
  { symbol: "4502.T", name: "Takeda Pharmaceutical", sector: "Gesundheit", region: "JP" },
  { symbol: "4503.T", name: "Astellas Pharma", sector: "Gesundheit", region: "JP" },
  { symbol: "4063.T", name: "Shin-Etsu Chemical", sector: "Rohstoffe", region: "JP" },
  { symbol: "4661.T", name: "Oriental Land", sector: "Konsum", region: "JP" },
  { symbol: "9983.T", name: "Fast Retailing (Uniqlo)", sector: "Konsum", region: "JP" },

  // === Weitere Welt-/Regional-ETFs ===
  { symbol: "URTH", name: "MSCI World (URTH)", sector: "Index", region: "US" },
  { symbol: "IOO", name: "S&P Global 100 (IOO)", sector: "Index", region: "US" },
  { symbol: "DAX", name: "Global X DAX Germany (DAX)", sector: "Index", region: "DE" },
  { symbol: "ISF.L", name: "iShares FTSE 100 (London)", sector: "Index", region: "UK" },
  { symbol: "VUKE.L", name: "Vanguard FTSE 100 (London)", sector: "Index", region: "UK" },
  { symbol: "CAC.PA", name: "Lyxor CAC 40 (Paris)", sector: "Index", region: "EU" },
  { symbol: "EXS1.DE", name: "iShares DAX (Xetra)", sector: "Index", region: "DE" },
  { symbol: "EXSA.DE", name: "iShares Stoxx Europe 600", sector: "Index", region: "EU" },
  { symbol: "1306.T", name: "Nomura TOPIX ETF", sector: "Index", region: "JP" },
  { symbol: "1321.T", name: "Nomura Nikkei 225 ETF", sector: "Index", region: "JP" },

  // === PRIORITÄT 1: Quantum Computing ===
  { symbol: "IONQ", name: "IonQ Inc.", sector: "Technologie", region: "US" },
  { symbol: "RGTI", name: "Rigetti Computing", sector: "Technologie", region: "US" },
  { symbol: "QBTS", name: "D-Wave Quantum", sector: "Technologie", region: "US" },
  { symbol: "QUBT", name: "Quantum Computing Inc.", sector: "Technologie", region: "US" },
  { symbol: "ARQQ", name: "Arqit Quantum", sector: "Technologie", region: "US" },
  { symbol: "QTUM", name: "Defiance Quantum ETF", sector: "Index", region: "US" },

  // === PRIORITÄT 1: AI / Voice / Data ===
  { symbol: "AI", name: "C3.ai Inc.", sector: "Technologie", region: "US" },
  { symbol: "SOUN", name: "SoundHound AI", sector: "Technologie", region: "US" },
  { symbol: "BBAI", name: "BigBear.ai Holdings", sector: "Technologie", region: "US" },
  { symbol: "VRSN", name: "VeriSign", sector: "Technologie", region: "US" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technologie", region: "US" },
  { symbol: "SNPS", name: "Synopsys", sector: "Technologie", region: "US" },
  { symbol: "ANSS", name: "Ansys", sector: "Technologie", region: "US" },

  // === PRIORITÄT 1: Hydrogen / Clean Energy ===
  { symbol: "BE", name: "Bloom Energy", sector: "Energie", region: "US" },
  { symbol: "BLDP", name: "Ballard Power Systems", sector: "Energie", region: "US" },
  { symbol: "FCEL", name: "FuelCell Energy", sector: "Energie", region: "US" },
  { symbol: "RUN", name: "Sunrun", sector: "Energie", region: "US" },
  { symbol: "NOVA", name: "Sunnova Energy", sector: "Energie", region: "US" },
  { symbol: "ARRY", name: "Array Technologies", sector: "Energie", region: "US" },
  { symbol: "SHLS", name: "Shoals Technologies", sector: "Energie", region: "US" },

  // === PRIORITÄT 1: Biotech / Gene Editing ===
  { symbol: "CRSP", name: "CRISPR Therapeutics", sector: "Gesundheit", region: "EU" },
  { symbol: "NTLA", name: "Intellia Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "EDIT", name: "Editas Medicine", sector: "Gesundheit", region: "US" },
  { symbol: "BEAM", name: "Beam Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "VERV", name: "Verve Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "RXRX", name: "Recursion Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "RCKT", name: "Rocket Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "SRPT", name: "Sarepta Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "IOVA", name: "Iovance Biotherapeutics", sector: "Gesundheit", region: "US" },

  // === S&P 500 Erweiterung (Industrie / Services) ===
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Technologie", region: "US" },
  { symbol: "PAYX", name: "Paychex", sector: "Technologie", region: "US" },
  { symbol: "FIS", name: "Fidelity National Information", sector: "Technologie", region: "US" },
  { symbol: "FI", name: "Fiserv", sector: "Technologie", region: "US" },
  { symbol: "GPN", name: "Global Payments", sector: "Technologie", region: "US" },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Finanzen", region: "US" },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Industrie", region: "US" },
  { symbol: "ROL", name: "Rollins", sector: "Industrie", region: "US" },
  { symbol: "CTAS", name: "Cintas", sector: "Industrie", region: "US" },
  { symbol: "WM", name: "Waste Management", sector: "Industrie", region: "US" },
  { symbol: "RSG", name: "Republic Services", sector: "Industrie", region: "US" },
  { symbol: "FAST", name: "Fastenal", sector: "Industrie", region: "US" },
  { symbol: "GWW", name: "W.W. Grainger", sector: "Industrie", region: "US" },
  { symbol: "PCAR", name: "PACCAR", sector: "Industrie", region: "US" },
  { symbol: "CMI", name: "Cummins", sector: "Industrie", region: "US" },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrie", region: "US" },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrie", region: "US" },
  { symbol: "XYL", name: "Xylem", sector: "Industrie", region: "US" },
  { symbol: "AME", name: "AMETEK", sector: "Industrie", region: "US" },
  { symbol: "FTV", name: "Fortive", sector: "Industrie", region: "US" },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrie", region: "US" },
  { symbol: "URI", name: "United Rentals", sector: "Industrie", region: "US" },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrie", region: "US" },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrie", region: "US" },
  { symbol: "CARR", name: "Carrier Global", sector: "Industrie", region: "US" },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrie", region: "US" },
  { symbol: "MAS", name: "Masco", sector: "Industrie", region: "US" },
  { symbol: "AOS", name: "A. O. Smith", sector: "Industrie", region: "US" },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrie", region: "US" },
  { symbol: "TT", name: "Trane Technologies", sector: "Industrie", region: "US" },
  { symbol: "LHX", name: "L3Harris Technologies", sector: "Industrie", region: "US" },
  { symbol: "TXT", name: "Textron", sector: "Industrie", region: "US" },
  { symbol: "HII", name: "Huntington Ingalls", sector: "Industrie", region: "US" },
  { symbol: "LDOS", name: "Leidos Holdings", sector: "Industrie", region: "US" },
  { symbol: "BAH", name: "Booz Allen Hamilton", sector: "Industrie", region: "US" },
  { symbol: "CACI", name: "CACI International", sector: "Industrie", region: "US" },
  { symbol: "KTOS", name: "Kratos Defense", sector: "Industrie", region: "US" },
  { symbol: "AVAV", name: "AeroVironment", sector: "Industrie", region: "US" },

  // === S&P 500 Konsum / Retail erweitert ===
  { symbol: "ROST", name: "Ross Stores", sector: "Konsum", region: "US" },
  { symbol: "DG", name: "Dollar General", sector: "Konsum", region: "US" },
  { symbol: "DLTR", name: "Dollar Tree", sector: "Konsum", region: "US" },
  { symbol: "KR", name: "Kroger", sector: "Konsum", region: "US" },
  { symbol: "SYY", name: "Sysco", sector: "Konsum", region: "US" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", sector: "Konsum", region: "US" },
  { symbol: "TSN", name: "Tyson Foods", sector: "Konsum", region: "US" },
  { symbol: "K", name: "Kellanova", sector: "Konsum", region: "US" },
  { symbol: "CAG", name: "Conagra Brands", sector: "Konsum", region: "US" },
  { symbol: "MKC", name: "McCormick", sector: "Konsum", region: "US" },
  { symbol: "STZ", name: "Constellation Brands", sector: "Konsum", region: "US" },
  { symbol: "MNST", name: "Monster Beverage", sector: "Konsum", region: "US" },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Konsum", region: "US" },
  { symbol: "BG", name: "Bunge", sector: "Konsum", region: "US" },
  { symbol: "CHD", name: "Church & Dwight", sector: "Konsum", region: "US" },
  { symbol: "CLX", name: "Clorox", sector: "Konsum", region: "US" },
  { symbol: "WBA", name: "Walgreens Boots Alliance", sector: "Gesundheit", region: "US" },

  // === S&P 500 Gesundheit erweitert ===
  { symbol: "HCA", name: "HCA Healthcare", sector: "Gesundheit", region: "US" },
  { symbol: "MCK", name: "McKesson", sector: "Gesundheit", region: "US" },
  { symbol: "COR", name: "Cencora", sector: "Gesundheit", region: "US" },
  { symbol: "CAH", name: "Cardinal Health", sector: "Gesundheit", region: "US" },
  { symbol: "DXCM", name: "Dexcom", sector: "Gesundheit", region: "US" },
  { symbol: "ALGN", name: "Align Technology", sector: "Gesundheit", region: "US" },
  { symbol: "RMD", name: "ResMed", sector: "Gesundheit", region: "US" },
  { symbol: "WAT", name: "Waters Corporation", sector: "Gesundheit", region: "US" },
  { symbol: "MTD", name: "Mettler-Toledo", sector: "Gesundheit", region: "US" },
  { symbol: "A", name: "Agilent Technologies", sector: "Gesundheit", region: "US" },
  { symbol: "PODD", name: "Insulet", sector: "Gesundheit", region: "US" },
  { symbol: "MOH", name: "Molina Healthcare", sector: "Gesundheit", region: "US" },
  { symbol: "CNC", name: "Centene", sector: "Gesundheit", region: "US" },
  { symbol: "INCY", name: "Incyte", sector: "Gesundheit", region: "US" },

  // === MDAX / SDAX (Deutschland) ===
  { symbol: "AFX.DE", name: "Carl Zeiss Meditec", sector: "Gesundheit", region: "DE" },
  { symbol: "AIXA.DE", name: "Aixtron", sector: "Technologie", region: "DE" },
  { symbol: "ARL.DE", name: "Aareal Bank", sector: "Finanzen", region: "DE" },
  { symbol: "BC8.DE", name: "Bechtle", sector: "Technologie", region: "DE" },
  { symbol: "BOSS.DE", name: "Hugo Boss", sector: "Konsum", region: "DE" },
  { symbol: "DUE.DE", name: "Dürr", sector: "Industrie", region: "DE" },
  { symbol: "EVK.DE", name: "Evonik Industries", sector: "Rohstoffe", region: "DE" },
  { symbol: "FNTN.DE", name: "freenet", sector: "Technologie", region: "DE" },
  { symbol: "FPE3.DE", name: "Fuchs Petrolub", sector: "Rohstoffe", region: "DE" },
  { symbol: "G1A.DE", name: "GEA Group", sector: "Industrie", region: "DE" },
  { symbol: "GXI.DE", name: "Gerresheimer", sector: "Gesundheit", region: "DE" },
  { symbol: "HNR1.DE", name: "Hannover Rück", sector: "Finanzen", region: "DE" },
  { symbol: "JUN3.DE", name: "Jungheinrich", sector: "Industrie", region: "DE" },
  { symbol: "KGX.DE", name: "Kion Group", sector: "Industrie", region: "DE" },
  { symbol: "LEG.DE", name: "LEG Immobilien", sector: "Finanzen", region: "DE" },
  { symbol: "LXS.DE", name: "Lanxess", sector: "Rohstoffe", region: "DE" },
  { symbol: "NDA.DE", name: "Aurubis", sector: "Rohstoffe", region: "DE" },
  { symbol: "NEM.DE", name: "Nemetschek", sector: "Technologie", region: "DE" },
  { symbol: "O2D.DE", name: "Telefónica Deutschland", sector: "Technologie", region: "DE" },
  { symbol: "PSM.DE", name: "ProSiebenSat.1", sector: "Konsum", region: "DE" },
  { symbol: "RAA.DE", name: "Rational AG", sector: "Industrie", region: "DE" },
  { symbol: "SOW.DE", name: "Software AG", sector: "Technologie", region: "DE" },
  { symbol: "TKA.DE", name: "ThyssenKrupp", sector: "Industrie", region: "DE" },
  { symbol: "TUI1.DE", name: "TUI", sector: "Konsum", region: "DE" },
  { symbol: "UN01.DE", name: "Uniper", sector: "Energie", region: "DE" },
  { symbol: "WCH.DE", name: "Wacker Chemie", sector: "Rohstoffe", region: "DE" },
  { symbol: "EVT.DE", name: "Evotec", sector: "Gesundheit", region: "DE" },
  { symbol: "MOR.DE", name: "MorphoSys", sector: "Gesundheit", region: "DE" },
  { symbol: "HAG.DE", name: "Hensoldt", sector: "Industrie", region: "DE" },
  { symbol: "R3NK.DE", name: "Renk Group", sector: "Industrie", region: "DE" },

  // === SMI (Schweiz) erweitert ===
  { symbol: "CFR.SW", name: "Richemont", sector: "Konsum", region: "EU" },
  { symbol: "UHR.SW", name: "Swatch Group", sector: "Konsum", region: "EU" },
  { symbol: "GEBN.SW", name: "Geberit", sector: "Industrie", region: "EU" },
  { symbol: "SLHN.SW", name: "Swiss Life Holding", sector: "Finanzen", region: "EU" },
  { symbol: "SREN.SW", name: "Swiss Re", sector: "Finanzen", region: "EU" },
  { symbol: "LONN.SW", name: "Lonza Group", sector: "Gesundheit", region: "EU" },
  { symbol: "ALC.SW", name: "Alcon", sector: "Gesundheit", region: "EU" },
  { symbol: "HOLN.SW", name: "Holcim", sector: "Rohstoffe", region: "EU" },
  { symbol: "SIKA.SW", name: "Sika", sector: "Rohstoffe", region: "EU" },
  { symbol: "PGHN.SW", name: "Partners Group", sector: "Finanzen", region: "EU" },
  { symbol: "KNIN.SW", name: "Kühne + Nagel", sector: "Industrie", region: "EU" },
  { symbol: "SCMN.SW", name: "Swisscom", sector: "Technologie", region: "EU" },

  // === AEX (Niederlande) ===
  { symbol: "ADYEN.AS", name: "Adyen", sector: "Finanzen", region: "EU" },
  { symbol: "PRX.AS", name: "Prosus", sector: "Technologie", region: "EU" },
  { symbol: "HEIA.AS", name: "Heineken", sector: "Konsum", region: "EU" },
  { symbol: "INGA.AS", name: "ING Groep", sector: "Finanzen", region: "EU" },
  { symbol: "PHIA.AS", name: "Philips", sector: "Gesundheit", region: "EU" },
  { symbol: "RAND.AS", name: "Randstad", sector: "Industrie", region: "EU" },
  { symbol: "WKL.AS", name: "Wolters Kluwer", sector: "Technologie", region: "EU" },
  { symbol: "AKZA.AS", name: "Akzo Nobel", sector: "Rohstoffe", region: "EU" },
  { symbol: "DSFIR.AS", name: "DSM-Firmenich", sector: "Rohstoffe", region: "EU" },
  { symbol: "MT.AS", name: "ArcelorMittal", sector: "Rohstoffe", region: "EU" },
  { symbol: "ASM.AS", name: "ASM International", sector: "Technologie", region: "EU" },
  { symbol: "BESI.AS", name: "BE Semiconductor", sector: "Technologie", region: "EU" },
  { symbol: "AD.AS", name: "Ahold Delhaize", sector: "Konsum", region: "EU" },

  // === FTSE 250 / UK erweitert ===
  { symbol: "IAG.L", name: "International Consolidated Airlines", sector: "Industrie", region: "UK" },
  { symbol: "EZJ.L", name: "easyJet", sector: "Industrie", region: "UK" },
  { symbol: "WTB.L", name: "Whitbread", sector: "Konsum", region: "UK" },
  { symbol: "MKS.L", name: "Marks & Spencer", sector: "Konsum", region: "UK" },
  { symbol: "NXT.L", name: "Next plc", sector: "Konsum", region: "UK" },
  { symbol: "JD.L", name: "JD Sports Fashion", sector: "Konsum", region: "UK" },
  { symbol: "ABF.L", name: "Associated British Foods", sector: "Konsum", region: "UK" },
  { symbol: "BNZL.L", name: "Bunzl", sector: "Industrie", region: "UK" },
  { symbol: "SMIN.L", name: "Smiths Group", sector: "Industrie", region: "UK" },
  { symbol: "WEIR.L", name: "Weir Group", sector: "Industrie", region: "UK" },
  { symbol: "ITRK.L", name: "Intertek Group", sector: "Industrie", region: "UK" },
  { symbol: "OCDO.L", name: "Ocado Group", sector: "Konsum", region: "UK" },

  // === Kanada ===
  { symbol: "RY", name: "Royal Bank of Canada", sector: "Finanzen", region: "US" },
  { symbol: "TD", name: "Toronto-Dominion Bank", sector: "Finanzen", region: "US" },
  { symbol: "BNS", name: "Bank of Nova Scotia", sector: "Finanzen", region: "US" },
  { symbol: "BMO", name: "Bank of Montreal", sector: "Finanzen", region: "US" },
  { symbol: "ENB", name: "Enbridge", sector: "Energie", region: "US" },
  { symbol: "TRP", name: "TC Energy", sector: "Energie", region: "US" },
  { symbol: "SU", name: "Suncor Energy", sector: "Energie", region: "US" },
  { symbol: "CNQ", name: "Canadian Natural Resources", sector: "Energie", region: "US" },
  { symbol: "CP", name: "Canadian Pacific Kansas City", sector: "Industrie", region: "US" },
  { symbol: "CNI", name: "Canadian National Railway", sector: "Industrie", region: "US" },
  { symbol: "MFC", name: "Manulife Financial", sector: "Finanzen", region: "US" },
  { symbol: "WCN", name: "Waste Connections", sector: "Industrie", region: "US" },
  { symbol: "TRI", name: "Thomson Reuters", sector: "Technologie", region: "US" },

  // === Australien (ASX) ===
  { symbol: "BHP.AX", name: "BHP Group (ASX)", sector: "Rohstoffe", region: "JP" },
  { symbol: "CBA.AX", name: "Commonwealth Bank of Australia", sector: "Finanzen", region: "JP" },
  { symbol: "CSL.AX", name: "CSL Limited", sector: "Gesundheit", region: "JP" },
  { symbol: "NAB.AX", name: "National Australia Bank", sector: "Finanzen", region: "JP" },
  { symbol: "WBC.AX", name: "Westpac Banking", sector: "Finanzen", region: "JP" },
  { symbol: "ANZ.AX", name: "ANZ Group", sector: "Finanzen", region: "JP" },
  { symbol: "WES.AX", name: "Wesfarmers", sector: "Konsum", region: "JP" },
  { symbol: "WOW.AX", name: "Woolworths Group", sector: "Konsum", region: "JP" },
  { symbol: "MQG.AX", name: "Macquarie Group", sector: "Finanzen", region: "JP" },
  { symbol: "FMG.AX", name: "Fortescue", sector: "Rohstoffe", region: "JP" },
  { symbol: "TLS.AX", name: "Telstra Group", sector: "Technologie", region: "JP" },

  // === Asien ADRs erweitert ===
  { symbol: "UMC", name: "United Microelectronics", sector: "Technologie", region: "JP" },
  { symbol: "ASX", name: "ASE Technology Holding", sector: "Technologie", region: "JP" },
  { symbol: "HDB", name: "HDFC Bank", sector: "Finanzen", region: "JP" },
  { symbol: "IBN", name: "ICICI Bank", sector: "Finanzen", region: "JP" },
  { symbol: "TTM", name: "Tata Motors", sector: "Konsum", region: "JP" },

  // === Defense / Europa ===
  { symbol: "LDO.MI", name: "Leonardo", sector: "Industrie", region: "EU" },
  { symbol: "SAAB-B.ST", name: "Saab AB", sector: "Industrie", region: "EU" },
];

// Deduplicated merge of base catalog + extended global universe.
// MERGE_STATS protokolliert, wie die einzelnen Quellen zusammengeführt wurden —
// vom Debug-/Admin-Panel ausgelesen.
export type MergeSource = "base" | "extra" | "extra2";
export type MergeStats = {
  mergedAt: number;
  buildTime: string;
  counts: { base: number; extra: number; extra2: number; total: number; duplicates: number };
  duplicatesBySource: { extra: string[]; extra2: string[] };
  perSource: Record<MergeSource, number>;
  sampleExtra2: string[];
};

const _seen = new Set<string>();
const _dupExtra: string[] = [];
const _dupExtra2: string[] = [];
const _perSource: Record<MergeSource, number> = { base: 0, extra: 0, extra2: 0 };

function _capForSource(src: MergeSource): Product["cap"] {
  // Heuristik: BASE = kuratierte Blue Chips/Mega-Caps, EXTRA = Mid Caps,
  // EXTRA2 = Small/Micro Caps. Reicht für saubere Bucket-Trennung in der UI.
  if (src === "base") return "large";
  if (src === "extra") return "mid";
  return "small";
}

function _mergeWith(list: Product[], src: MergeSource, dupSink?: string[]): Product[] {
  const out: Product[] = [];
  const defaultCap = _capForSource(src);
  for (const p of list) {
    const key = p.symbol.toUpperCase();
    if (_seen.has(key)) { dupSink?.push(key); continue; }
    _seen.add(key);
    _perSource[src]++;
    out.push({ ...p, cap: p.cap ?? defaultCap });
  }
  return out;
}

const _mergedBase = _mergeWith(PRODUCTS_BASE, "base");
const _mergedExtra = _mergeWith(PRODUCTS_EXTRA, "extra", _dupExtra);
const _mergedExtra2 = _mergeWith(PRODUCTS_EXTRA2, "extra2", _dupExtra2);


export const PRODUCTS: Product[] = [..._mergedBase, ..._mergedExtra, ..._mergedExtra2];

export const MERGE_STATS: MergeStats = {
  mergedAt: Date.now(),
  buildTime: new Date().toISOString(),
  counts: {
    base: PRODUCTS_BASE.length,
    extra: PRODUCTS_EXTRA.length,
    extra2: PRODUCTS_EXTRA2.length,
    total: PRODUCTS.length,
    duplicates: _dupExtra.length + _dupExtra2.length,
  },
  duplicatesBySource: { extra: _dupExtra, extra2: _dupExtra2 },
  perSource: _perSource,
  sampleExtra2: _mergedExtra2.slice(0, 20).map((p) => p.symbol),
};

export const SECTORS = ["Technologie", "Energie", "Finanzen", "Gesundheit", "Konsum", "Industrie", "Rohstoffe"] as const;

// Vorbereitete Indizes — einmalig beim Modul-Load berechnet. Verhindert,
// dass Komponenten bei jedem Render 3.300+ Symbole linear durchsuchen.
export const PRODUCT_BY_SYMBOL: ReadonlyMap<string, Product> = new Map(
  PRODUCTS.map((p) => [p.symbol.toUpperCase(), p]),
);
export const PRODUCTS_BY_SECTOR: ReadonlyMap<string, Product[]> = (() => {
  const m = new Map<string, Product[]>();
  for (const p of PRODUCTS) {
    let arr = m.get(p.sector);
    if (!arr) { arr = []; m.set(p.sector, arr); }
    arr.push(p);
  }
  return m;
})();

export const INDICES = PRODUCTS_BY_SECTOR.get("Index") ?? [];
export const BENCHMARK = "SPY";

export function findProduct(symbol: string): Product | undefined {
  return PRODUCT_BY_SYMBOL.get(symbol.toUpperCase());
}

// Optionales Limit verhindert pathologische Renderzeiten bei generischen Queries.
export function searchProducts(q: string, limit?: number): Product[] {
  const s = q.trim().toLowerCase();
  if (!s) return limit ? PRODUCTS.slice(0, limit) : PRODUCTS;
  const out: Product[] = [];
  const cap = limit ?? PRODUCTS.length;
  for (const p of PRODUCTS) {
    if (p.symbol.toLowerCase().includes(s) || p.name.toLowerCase().includes(s)) {
      out.push(p);
      if (out.length >= cap) break;
    }
  }
  return out;
}
