// Auto-generated extension — 500+ additional global tickers.
import type { Product } from "./products";

export const PRODUCTS_EXTRA: Product[] = [
  { symbol: "LULU", name: "Lululemon Athletica", sector: "Konsum", region: "US" },
  { symbol: "TAP", name: "Molson Coors", sector: "Konsum", region: "US" },
  { symbol: "CPB", name: "Campbell Soup", sector: "Konsum", region: "US" },
  { symbol: "SJM", name: "J.M. Smucker", sector: "Konsum", region: "US" },
  { symbol: "HRL", name: "Hormel Foods", sector: "Konsum", region: "US" },
  { symbol: "POST", name: "Post Holdings", sector: "Konsum", region: "US" },
  { symbol: "LW", name: "Lamb Weston", sector: "Konsum", region: "US" },
  { symbol: "USFD", name: "US Foods", sector: "Konsum", region: "US" },
  { symbol: "PFGC", name: "Performance Food Group", sector: "Konsum", region: "US" },
  { symbol: "EXPE", name: "Expedia", sector: "Konsum", region: "US" },
  { symbol: "H", name: "Hyatt Hotels", sector: "Konsum", region: "US" },
  { symbol: "CHH", name: "Choice Hotels", sector: "Konsum", region: "US" },
  { symbol: "WH", name: "Wyndham Hotels", sector: "Konsum", region: "US" },
  { symbol: "RCL", name: "Royal Caribbean", sector: "Konsum", region: "US" },
  { symbol: "CCL", name: "Carnival", sector: "Konsum", region: "US" },
  { symbol: "NCLH", name: "Norwegian Cruise", sector: "Konsum", region: "US" },
  { symbol: "ALK", name: "Alaska Air", sector: "Industrie", region: "US" },
  { symbol: "JBLU", name: "JetBlue", sector: "Industrie", region: "US" },
  { symbol: "SAVE", name: "Spirit Airlines", sector: "Industrie", region: "US" },
  { symbol: "HA", name: "Hawaiian Holdings", sector: "Industrie", region: "US" },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Konsum", region: "US" },
  { symbol: "CZR", name: "Caesars Entertainment", sector: "Konsum", region: "US" },
  { symbol: "PENN", name: "PENN Entertainment", sector: "Konsum", region: "US" },
  { symbol: "FLUT", name: "Flutter Entertainment", sector: "Konsum", region: "US" },
  { symbol: "BYD", name: "Boyd Gaming", sector: "Konsum", region: "US" },
  { symbol: "RRR", name: "Red Rock Resorts", sector: "Konsum", region: "US" },
  { symbol: "CHDN", name: "Churchill Downs", sector: "Konsum", region: "US" },
  { symbol: "QSR", name: "Restaurant Brands", sector: "Konsum", region: "US" },
  { symbol: "DPZ", name: "Dominos Pizza", sector: "Konsum", region: "US" },
  { symbol: "WEN", name: "Wendys", sector: "Konsum", region: "US" },
  { symbol: "JACK", name: "Jack in the Box", sector: "Konsum", region: "US" },
  { symbol: "DRI", name: "Darden Restaurants", sector: "Konsum", region: "US" },
  { symbol: "EAT", name: "Brinker International", sector: "Konsum", region: "US" },
  { symbol: "TXRH", name: "Texas Roadhouse", sector: "Konsum", region: "US" },
  { symbol: "CAKE", name: "Cheesecake Factory", sector: "Konsum", region: "US" },
  { symbol: "BLMN", name: "Bloomin Brands", sector: "Konsum", region: "US" },
  { symbol: "SHAK", name: "Shake Shack", sector: "Konsum", region: "US" },
  { symbol: "WING", name: "Wingstop", sector: "Konsum", region: "US" },
  { symbol: "PLAY", name: "Dave & Busters", sector: "Konsum", region: "US" },
  { symbol: "SBH", name: "Sally Beauty", sector: "Konsum", region: "US" },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Konsum", region: "US" },
  { symbol: "BBWI", name: "Bath & Body Works", sector: "Konsum", region: "US" },
  { symbol: "VSCO", name: "Victorias Secret", sector: "Konsum", region: "US" },
  { symbol: "PVH", name: "PVH Corp", sector: "Konsum", region: "US" },
  { symbol: "RL", name: "Ralph Lauren", sector: "Konsum", region: "US" },
  { symbol: "TPR", name: "Tapestry", sector: "Konsum", region: "US" },
  { symbol: "CPRI", name: "Capri Holdings", sector: "Konsum", region: "US" },
  { symbol: "UAA", name: "Under Armour A", sector: "Konsum", region: "US" },
  { symbol: "UA", name: "Under Armour C", sector: "Konsum", region: "US" },
  { symbol: "HBI", name: "Hanesbrands", sector: "Konsum", region: "US" },
  { symbol: "GIL", name: "Gildan Activewear", sector: "Konsum", region: "US" },
  { symbol: "CROX", name: "Crocs", sector: "Konsum", region: "US" },
  { symbol: "DECK", name: "Deckers Outdoor", sector: "Konsum", region: "US" },
  { symbol: "SKX", name: "Skechers", sector: "Konsum", region: "US" },
  { symbol: "FL", name: "Foot Locker", sector: "Konsum", region: "US" },
  { symbol: "KSS", name: "Kohls", sector: "Konsum", region: "US" },
  { symbol: "M", name: "Macys", sector: "Konsum", region: "US" },
  { symbol: "JWN", name: "Nordstrom", sector: "Konsum", region: "US" },
  { symbol: "GPS", name: "Gap", sector: "Konsum", region: "US" },
  { symbol: "URBN", name: "Urban Outfitters", sector: "Konsum", region: "US" },
  { symbol: "AEO", name: "American Eagle", sector: "Konsum", region: "US" },
  { symbol: "PETS", name: "PetMed Express", sector: "Konsum", region: "US" },
  { symbol: "RAD", name: "Rite Aid", sector: "Konsum", region: "US" },
  { symbol: "BJ", name: "BJs Wholesale", sector: "Konsum", region: "US" },
  { symbol: "BIG", name: "Big Lots", sector: "Konsum", region: "US" },
  { symbol: "FIVE", name: "Five Below", sector: "Konsum", region: "US" },
  { symbol: "OLLI", name: "Ollies Bargain", sector: "Konsum", region: "US" },
  { symbol: "BURL", name: "Burlington Stores", sector: "Konsum", region: "US" },
  { symbol: "D", name: "Dominion Energy", sector: "Energie", region: "US" },
  { symbol: "XEL", name: "Xcel Energy", sector: "Energie", region: "US" },
  { symbol: "SRE", name: "Sempra", sector: "Energie", region: "US" },
  { symbol: "PEG", name: "Public Service Enterprise", sector: "Energie", region: "US" },
  { symbol: "ED", name: "Consolidated Edison", sector: "Energie", region: "US" },
  { symbol: "EIX", name: "Edison International", sector: "Energie", region: "US" },
  { symbol: "PCG", name: "PG&E", sector: "Energie", region: "US" },
  { symbol: "AEE", name: "Ameren", sector: "Energie", region: "US" },
  { symbol: "WEC", name: "WEC Energy", sector: "Energie", region: "US" },
  { symbol: "ETR", name: "Entergy", sector: "Energie", region: "US" },
  { symbol: "DTE", name: "DTE Energy", sector: "Energie", region: "US" },
  { symbol: "FE", name: "FirstEnergy", sector: "Energie", region: "US" },
  { symbol: "PPL", name: "PPL Corp", sector: "Energie", region: "US" },
  { symbol: "CMS", name: "CMS Energy", sector: "Energie", region: "US" },
  { symbol: "AES", name: "AES Corp", sector: "Energie", region: "US" },
  { symbol: "NRG", name: "NRG Energy", sector: "Energie", region: "US" },
  { symbol: "PXD", name: "Pioneer Natural", sector: "Energie", region: "US" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energie", region: "US" },
  { symbol: "DVN", name: "Devon Energy", sector: "Energie", region: "US" },
  { symbol: "APA", name: "APA Corp", sector: "Energie", region: "US" },
  { symbol: "MRO", name: "Marathon Oil", sector: "Energie", region: "US" },
  { symbol: "HES", name: "Hess", sector: "Energie", region: "US" },
  { symbol: "OKE", name: "Oneok", sector: "Energie", region: "US" },
  { symbol: "ET", name: "Energy Transfer", sector: "Energie", region: "US" },
  { symbol: "MPLX", name: "MPLX", sector: "Energie", region: "US" },
  { symbol: "EPD", name: "Enterprise Products", sector: "Energie", region: "US" },
  { symbol: "PAA", name: "Plains All American", sector: "Energie", region: "US" },
  { symbol: "TRGP", name: "Targa Resources", sector: "Energie", region: "US" },
  { symbol: "HAL", name: "Halliburton", sector: "Energie", region: "US" },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energie", region: "US" },
  { symbol: "FTI", name: "TechnipFMC", sector: "Energie", region: "US" },
  { symbol: "NOV", name: "NOV Inc", sector: "Energie", region: "US" },
  { symbol: "CHK", name: "Chesapeake Energy", sector: "Energie", region: "US" },
  { symbol: "AR", name: "Antero Resources", sector: "Energie", region: "US" },
  { symbol: "RRC", name: "Range Resources", sector: "Energie", region: "US" },
  { symbol: "SWN", name: "Southwestern Energy", sector: "Energie", region: "US" },
  { symbol: "CTRA", name: "Coterra Energy", sector: "Energie", region: "US" },
  { symbol: "OVV", name: "Ovintiv", sector: "Energie", region: "US" },
  { symbol: "MUR", name: "Murphy Oil", sector: "Energie", region: "US" },
  { symbol: "CVI", name: "CVR Energy", sector: "Energie", region: "US" },
  { symbol: "PBF", name: "PBF Energy", sector: "Energie", region: "US" },
  { symbol: "DK", name: "Delek US", sector: "Energie", region: "US" },
  { symbol: "SGEN", name: "Seagen", sector: "Gesundheit", region: "US" },
  { symbol: "BMRN", name: "BioMarin", sector: "Gesundheit", region: "US" },
  { symbol: "EXEL", name: "Exelixis", sector: "Gesundheit", region: "US" },
  { symbol: "HALO", name: "Halozyme", sector: "Gesundheit", region: "US" },
  { symbol: "NBIX", name: "Neurocrine Biosciences", sector: "Gesundheit", region: "US" },
  { symbol: "UTHR", name: "United Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "IONS", name: "Ionis Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "BLUE", name: "bluebird bio", sector: "Gesundheit", region: "US" },
  { symbol: "ARWR", name: "Arrowhead Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "SAGE", name: "Sage Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "ACAD", name: "ACADIA Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "PTCT", name: "PTC Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "RARE", name: "Ultragenyx", sector: "Gesundheit", region: "US" },
  { symbol: "FOLD", name: "Amicus Therapeutics", sector: "Gesundheit", region: "US" },
  { symbol: "KRYS", name: "Krystal Biotech", sector: "Gesundheit", region: "US" },
  { symbol: "RYTM", name: "Rhythm Pharmaceuticals", sector: "Gesundheit", region: "US" },
  { symbol: "ITCI", name: "Intra-Cellular", sector: "Gesundheit", region: "US" },
  { symbol: "UHS", name: "Universal Health Services", sector: "Gesundheit", region: "US" },
  { symbol: "THC", name: "Tenet Healthcare", sector: "Gesundheit", region: "US" },
  { symbol: "DGX", name: "Quest Diagnostics", sector: "Gesundheit", region: "US" },
  { symbol: "LH", name: "Labcorp", sector: "Gesundheit", region: "US" },
  { symbol: "IQV", name: "IQVIA", sector: "Gesundheit", region: "US" },
  { symbol: "CRL", name: "Charles River Labs", sector: "Gesundheit", region: "US" },
  { symbol: "BAX", name: "Baxter", sector: "Gesundheit", region: "US" },
  { symbol: "HOLX", name: "Hologic", sector: "Gesundheit", region: "US" },
  { symbol: "TNDM", name: "Tandem Diabetes", sector: "Gesundheit", region: "US" },
  { symbol: "OMI", name: "Owens & Minor", sector: "Gesundheit", region: "US" },
  { symbol: "PEN", name: "Penumbra", sector: "Gesundheit", region: "US" },
  { symbol: "MASI", name: "Masimo", sector: "Gesundheit", region: "US" },
  { symbol: "NVCR", name: "NovoCure", sector: "Gesundheit", region: "US" },
  { symbol: "INSP", name: "Inspire Medical", sector: "Gesundheit", region: "US" },
  { symbol: "STAA", name: "STAAR Surgical", sector: "Gesundheit", region: "US" },
  { symbol: "LMAT", name: "LeMaitre Vascular", sector: "Gesundheit", region: "US" },
  { symbol: "BX", name: "Blackstone", sector: "Finanzen", region: "US" },
  { symbol: "KKR", name: "KKR & Co", sector: "Finanzen", region: "US" },
  { symbol: "APO", name: "Apollo Global", sector: "Finanzen", region: "US" },
  { symbol: "CG", name: "Carlyle Group", sector: "Finanzen", region: "US" },
  { symbol: "ARES", name: "Ares Management", sector: "Finanzen", region: "US" },
  { symbol: "TROW", name: "T. Rowe Price", sector: "Finanzen", region: "US" },
  { symbol: "IVZ", name: "Invesco", sector: "Finanzen", region: "US" },
  { symbol: "BEN", name: "Franklin Resources", sector: "Finanzen", region: "US" },
  { symbol: "LAZ", name: "Lazard", sector: "Finanzen", region: "US" },
  { symbol: "EVR", name: "Evercore", sector: "Finanzen", region: "US" },
  { symbol: "MC", name: "Moelis", sector: "Finanzen", region: "US" },
  { symbol: "PIPR", name: "Piper Sandler", sector: "Finanzen", region: "US" },
  { symbol: "HLNE", name: "Hamilton Lane", sector: "Finanzen", region: "US" },
  { symbol: "STT", name: "State Street", sector: "Finanzen", region: "US" },
  { symbol: "BK", name: "Bank of NY Mellon", sector: "Finanzen", region: "US" },
  { symbol: "NTRS", name: "Northern Trust", sector: "Finanzen", region: "US" },
  { symbol: "HIG", name: "Hartford Financial", sector: "Finanzen", region: "US" },
  { symbol: "PGR", name: "Progressive", sector: "Finanzen", region: "US" },
  { symbol: "AFL", name: "Aflac", sector: "Finanzen", region: "US" },
  { symbol: "WTW", name: "Willis Towers Watson", sector: "Finanzen", region: "US" },
  { symbol: "AJG", name: "Arthur J. Gallagher", sector: "Finanzen", region: "US" },
  { symbol: "BRO", name: "Brown & Brown", sector: "Finanzen", region: "US" },
  { symbol: "RJF", name: "Raymond James", sector: "Finanzen", region: "US" },
  { symbol: "LPLA", name: "LPL Financial", sector: "Finanzen", region: "US" },
  { symbol: "MKTX", name: "MarketAxess", sector: "Finanzen", region: "US" },
  { symbol: "FDS", name: "FactSet", sector: "Finanzen", region: "US" },
  { symbol: "MORN", name: "Morningstar", sector: "Finanzen", region: "US" },
  { symbol: "FICO", name: "Fair Isaac", sector: "Finanzen", region: "US" },
  { symbol: "EFX", name: "Equifax", sector: "Finanzen", region: "US" },
  { symbol: "TRU", name: "TransUnion", sector: "Finanzen", region: "US" },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Finanzen", region: "US" },
  { symbol: "ALLY", name: "Ally Financial", sector: "Finanzen", region: "US" },
  { symbol: "AMP", name: "Ameriprise", sector: "Finanzen", region: "US" },
  { symbol: "DLR", name: "Digital Realty", sector: "Finanzen", region: "US" },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Finanzen", region: "US" },
  { symbol: "AVB", name: "AvalonBay", sector: "Finanzen", region: "US" },
  { symbol: "EQR", name: "Equity Residential", sector: "Finanzen", region: "US" },
  { symbol: "ESS", name: "Essex Property", sector: "Finanzen", region: "US" },
  { symbol: "MAA", name: "Mid-America Apartment", sector: "Finanzen", region: "US" },
  { symbol: "UDR", name: "UDR Inc", sector: "Finanzen", region: "US" },
  { symbol: "CPT", name: "Camden Property", sector: "Finanzen", region: "US" },
  { symbol: "INVH", name: "Invitation Homes", sector: "Finanzen", region: "US" },
  { symbol: "AMH", name: "American Homes 4 Rent", sector: "Finanzen", region: "US" },
  { symbol: "WELL", name: "Welltower", sector: "Finanzen", region: "US" },
  { symbol: "VTR", name: "Ventas", sector: "Finanzen", region: "US" },
  { symbol: "PEAK", name: "Healthpeak", sector: "Finanzen", region: "US" },
  { symbol: "OHI", name: "Omega Healthcare", sector: "Finanzen", region: "US" },
  { symbol: "ARE", name: "Alexandria Real Estate", sector: "Finanzen", region: "US" },
  { symbol: "BXP", name: "Boston Properties", sector: "Finanzen", region: "US" },
  { symbol: "VNO", name: "Vornado Realty", sector: "Finanzen", region: "US" },
  { symbol: "SLG", name: "SL Green Realty", sector: "Finanzen", region: "US" },
  { symbol: "KIM", name: "Kimco Realty", sector: "Finanzen", region: "US" },
  { symbol: "REG", name: "Regency Centers", sector: "Finanzen", region: "US" },
  { symbol: "FRT", name: "Federal Realty", sector: "Finanzen", region: "US" },
  { symbol: "BRX", name: "Brixmor Property", sector: "Finanzen", region: "US" },
  { symbol: "MAC", name: "Macerich", sector: "Finanzen", region: "US" },
  { symbol: "NNN", name: "NNN REIT", sector: "Finanzen", region: "US" },
  { symbol: "STAG", name: "Stag Industrial", sector: "Finanzen", region: "US" },
  { symbol: "FR", name: "First Industrial", sector: "Finanzen", region: "US" },
  { symbol: "REXR", name: "Rexford Industrial", sector: "Finanzen", region: "US" },
  { symbol: "EGP", name: "EastGroup Properties", sector: "Finanzen", region: "US" },
  { symbol: "IRM", name: "Iron Mountain", sector: "Finanzen", region: "US" },
  { symbol: "HST", name: "Host Hotels", sector: "Finanzen", region: "US" },
  { symbol: "RHP", name: "Ryman Hospitality", sector: "Finanzen", region: "US" },
  { symbol: "APLE", name: "Apple Hospitality", sector: "Finanzen", region: "US" },
  { symbol: "DRH", name: "DiamondRock", sector: "Finanzen", region: "US" },
  { symbol: "PEB", name: "Pebblebrook", sector: "Finanzen", region: "US" },
  { symbol: "HEI", name: "HEICO", sector: "Industrie", region: "US" },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Industrie", region: "US" },
  { symbol: "SAIC", name: "SAIC", sector: "Industrie", region: "US" },
  { symbol: "MRCY", name: "Mercury Systems", sector: "Industrie", region: "US" },
  { symbol: "CW", name: "Curtiss-Wright", sector: "Industrie", region: "US" },
  { symbol: "MOG.A", name: "Moog Inc", sector: "Industrie", region: "US" },
  { symbol: "WWD", name: "Woodward", sector: "Industrie", region: "US" },
  { symbol: "HEI.A", name: "HEICO Class A", sector: "Industrie", region: "US" },
  { symbol: "AGCO", name: "AGCO", sector: "Industrie", region: "US" },
  { symbol: "CNHI", name: "CNH Industrial", sector: "Industrie", region: "US" },
  { symbol: "WAB", name: "Westinghouse Air Brake", sector: "Industrie", region: "US" },
  { symbol: "PNR", name: "Pentair", sector: "Industrie", region: "US" },
  { symbol: "WTS", name: "Watts Water", sector: "Industrie", region: "US" },
  { symbol: "MSM", name: "MSC Industrial", sector: "Industrie", region: "US" },
  { symbol: "HUBB", name: "Hubbell", sector: "Industrie", region: "US" },
  { symbol: "ROP", name: "Roper Technologies", sector: "Industrie", region: "US" },
  { symbol: "LII", name: "Lennox International", sector: "Industrie", region: "US" },
  { symbol: "FLS", name: "Flowserve", sector: "Industrie", region: "US" },
  { symbol: "GGG", name: "Graco", sector: "Industrie", region: "US" },
  { symbol: "NDSN", name: "Nordson", sector: "Industrie", region: "US" },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Industrie", region: "US" },
  { symbol: "EXPD", name: "Expeditors", sector: "Industrie", region: "US" },
  { symbol: "JBHT", name: "J.B. Hunt", sector: "Industrie", region: "US" },
  { symbol: "ODFL", name: "Old Dominion", sector: "Industrie", region: "US" },
  { symbol: "XPO", name: "XPO Inc", sector: "Industrie", region: "US" },
  { symbol: "KNX", name: "Knight-Swift", sector: "Industrie", region: "US" },
  { symbol: "WERN", name: "Werner Enterprises", sector: "Industrie", region: "US" },
  { symbol: "LSTR", name: "Landstar", sector: "Industrie", region: "US" },
  { symbol: "R", name: "Ryder System", sector: "Industrie", region: "US" },
  { symbol: "MTZ", name: "MasTec", sector: "Industrie", region: "US" },
  { symbol: "EME", name: "EMCOR Group", sector: "Industrie", region: "US" },
  { symbol: "ACM", name: "AECOM", sector: "Industrie", region: "US" },
  { symbol: "FLR", name: "Fluor", sector: "Industrie", region: "US" },
  { symbol: "J", name: "Jacobs Solutions", sector: "Industrie", region: "US" },
  { symbol: "PRIM", name: "Primoris Services", sector: "Industrie", region: "US" },
  { symbol: "MYR", name: "MYR Group", sector: "Industrie", region: "US" },
  { symbol: "STRL", name: "Sterling Infrastructure", sector: "Industrie", region: "US" },
  { symbol: "ROAD", name: "Construction Partners", sector: "Industrie", region: "US" },
  { symbol: "EXP", name: "Eagle Materials", sector: "Industrie", region: "US" },
  { symbol: "VMC", name: "Vulcan Materials", sector: "Industrie", region: "US" },
  { symbol: "MLM", name: "Martin Marietta", sector: "Industrie", region: "US" },
  { symbol: "USCR", name: "U.S. Concrete", sector: "Industrie", region: "US" },
  { symbol: "SUM", name: "Summit Materials", sector: "Industrie", region: "US" },
  { symbol: "RPM", name: "RPM International", sector: "Rohstoffe", region: "US" },
  { symbol: "LYB", name: "LyondellBasell", sector: "Rohstoffe", region: "US" },
  { symbol: "EMN", name: "Eastman Chemical", sector: "Rohstoffe", region: "US" },
  { symbol: "CE", name: "Celanese", sector: "Rohstoffe", region: "US" },
  { symbol: "ALB", name: "Albemarle", sector: "Rohstoffe", region: "US" },
  { symbol: "FMC", name: "FMC Corp", sector: "Rohstoffe", region: "US" },
  { symbol: "NTR", name: "Nutrien", sector: "Rohstoffe", region: "US" },
  { symbol: "SQM", name: "SQM", sector: "Rohstoffe", region: "US" },
  { symbol: "IFF", name: "International Flavors", sector: "Rohstoffe", region: "US" },
  { symbol: "AVY", name: "Avery Dennison", sector: "Rohstoffe", region: "US" },
  { symbol: "PKG", name: "Packaging Corp", sector: "Rohstoffe", region: "US" },
  { symbol: "IP", name: "International Paper", sector: "Rohstoffe", region: "US" },
  { symbol: "WRK", name: "WestRock", sector: "Rohstoffe", region: "US" },
  { symbol: "SON", name: "Sonoco Products", sector: "Rohstoffe", region: "US" },
  { symbol: "AMCR", name: "Amcor", sector: "Rohstoffe", region: "US" },
  { symbol: "BERY", name: "Berry Global", sector: "Rohstoffe", region: "US" },
  { symbol: "SEE", name: "Sealed Air", sector: "Rohstoffe", region: "US" },
  { symbol: "ATR", name: "AptarGroup", sector: "Rohstoffe", region: "US" },
  { symbol: "CCK", name: "Crown Holdings", sector: "Rohstoffe", region: "US" },
  { symbol: "BLL", name: "Ball Corp", sector: "Rohstoffe", region: "US" },
  { symbol: "OI", name: "O-I Glass", sector: "Rohstoffe", region: "US" },
  { symbol: "KGC", name: "Kinross Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "AU", name: "AngloGold Ashanti", sector: "Rohstoffe", region: "US" },
  { symbol: "HMY", name: "Harmony Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "GFI", name: "Gold Fields", sector: "Rohstoffe", region: "US" },
  { symbol: "PAAS", name: "Pan American Silver", sector: "Rohstoffe", region: "US" },
  { symbol: "AG", name: "First Majestic Silver", sector: "Rohstoffe", region: "US" },
  { symbol: "CDE", name: "Coeur Mining", sector: "Rohstoffe", region: "US" },
  { symbol: "HL", name: "Hecla Mining", sector: "Rohstoffe", region: "US" },
  { symbol: "WPM", name: "Wheaton Precious Metals", sector: "Rohstoffe", region: "US" },
  { symbol: "FNV", name: "Franco-Nevada", sector: "Rohstoffe", region: "US" },
  { symbol: "RGLD", name: "Royal Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "SAND", name: "Sandstorm Gold", sector: "Rohstoffe", region: "US" },
  { symbol: "X", name: "US Steel", sector: "Rohstoffe", region: "US" },
  { symbol: "RS", name: "Reliance Inc", sector: "Rohstoffe", region: "US" },
  { symbol: "CMC", name: "Commercial Metals", sector: "Rohstoffe", region: "US" },
  { symbol: "ATI", name: "ATI Inc", sector: "Rohstoffe", region: "US" },
  { symbol: "CRS", name: "Carpenter Technology", sector: "Rohstoffe", region: "US" },
  { symbol: "HAYN", name: "Haynes International", sector: "Rohstoffe", region: "US" },
  { symbol: "USAP", name: "Universal Stainless", sector: "Rohstoffe", region: "US" },
  { symbol: "MP", name: "MP Materials", sector: "Rohstoffe", region: "US" },
  { symbol: "LAC", name: "Lithium Americas", sector: "Rohstoffe", region: "US" },
  { symbol: "SGML", name: "Sigma Lithium", sector: "Rohstoffe", region: "US" },
  { symbol: "PLL", name: "Piedmont Lithium", sector: "Rohstoffe", region: "US" },
  { symbol: "LTHM", name: "Livent", sector: "Rohstoffe", region: "US" },
  { symbol: "CCJ", name: "Cameco", sector: "Rohstoffe", region: "US" },
  { symbol: "UEC", name: "Uranium Energy", sector: "Rohstoffe", region: "US" },
  { symbol: "DNN", name: "Denison Mines", sector: "Rohstoffe", region: "US" },
  { symbol: "UUUU", name: "Energy Fuels", sector: "Rohstoffe", region: "US" },
  { symbol: "URG", name: "Ur-Energy", sector: "Rohstoffe", region: "US" },
  { symbol: "ESTC", name: "Elastic", sector: "Technologie", region: "US" },
  { symbol: "CFLT", name: "Confluent", sector: "Technologie", region: "US" },
  { symbol: "FROG", name: "JFrog", sector: "Technologie", region: "US" },
  { symbol: "HCP", name: "HashiCorp", sector: "Technologie", region: "US" },
  { symbol: "GTLB", name: "GitLab", sector: "Technologie", region: "US" },
  { symbol: "VEEV", name: "Veeva Systems", sector: "Technologie", region: "US" },
  { symbol: "BILL", name: "BILL Holdings", sector: "Technologie", region: "US" },
  { symbol: "PCTY", name: "Paylocity", sector: "Technologie", region: "US" },
  { symbol: "PAYC", name: "Paycom", sector: "Technologie", region: "US" },
  { symbol: "PCOR", name: "Procore", sector: "Technologie", region: "US" },
  { symbol: "RNG", name: "RingCentral", sector: "Technologie", region: "US" },
  { symbol: "FIVN", name: "Five9", sector: "Technologie", region: "US" },
  { symbol: "NICE", name: "NICE Ltd", sector: "Technologie", region: "US" },
  { symbol: "HUBS", name: "HubSpot", sector: "Technologie", region: "US" },
  { symbol: "MNDY", name: "Monday.com", sector: "Technologie", region: "US" },
  { symbol: "ASAN", name: "Asana", sector: "Technologie", region: "US" },
  { symbol: "SMAR", name: "Smartsheet", sector: "Technologie", region: "US" },
  { symbol: "BOX", name: "Box", sector: "Technologie", region: "US" },
  { symbol: "DBX", name: "Dropbox", sector: "Technologie", region: "US" },
  { symbol: "WIX", name: "Wix.com", sector: "Technologie", region: "US" },
  { symbol: "SQSP", name: "Squarespace", sector: "Technologie", region: "US" },
  { symbol: "GDDY", name: "GoDaddy", sector: "Technologie", region: "US" },
  { symbol: "AKAM", name: "Akamai", sector: "Technologie", region: "US" },
  { symbol: "FFIV", name: "F5 Inc", sector: "Technologie", region: "US" },
  { symbol: "CHKP", name: "Check Point Software", sector: "Technologie", region: "US" },
  { symbol: "CYBR", name: "CyberArk", sector: "Technologie", region: "US" },
  { symbol: "RPD", name: "Rapid7", sector: "Technologie", region: "US" },
  { symbol: "TENB", name: "Tenable", sector: "Technologie", region: "US" },
  { symbol: "VRNS", name: "Varonis", sector: "Technologie", region: "US" },
  { symbol: "QLYS", name: "Qualys", sector: "Technologie", region: "US" },
  { symbol: "SPLK", name: "Splunk", sector: "Technologie", region: "US" },
  { symbol: "DT", name: "Dynatrace", sector: "Technologie", region: "US" },
  { symbol: "PD", name: "PagerDuty", sector: "Technologie", region: "US" },
  { symbol: "APPN", name: "Appian", sector: "Technologie", region: "US" },
  { symbol: "AYX", name: "Alteryx", sector: "Technologie", region: "US" },
  { symbol: "BRZE", name: "Braze", sector: "Technologie", region: "US" },
  { symbol: "ZI", name: "ZoomInfo", sector: "Technologie", region: "US" },
  { symbol: "DTG.DE", name: "Daimler Truck", sector: "Industrie", region: "DE" },
  { symbol: "FME.DE", name: "Fresenius Medical Care", sector: "Gesundheit", region: "DE" },
  { symbol: "MRK.DE", name: "Merck KGaA", sector: "Gesundheit", region: "DE" },
  { symbol: "BNR.DE", name: "Brenntag", sector: "Rohstoffe", region: "DE" },
  { symbol: "LIN.DE", name: "Linde plc", sector: "Rohstoffe", region: "DE" },
  { symbol: "UTDI.DE", name: "United Internet", sector: "Technologie", region: "DE" },
  { symbol: "WAF.DE", name: "Siltronic", sector: "Technologie", region: "DE" },
  { symbol: "EVO.ST", name: "Evolution AB", sector: "Konsum", region: "EU" },
  { symbol: "SAND.ST", name: "Sandvik", sector: "Industrie", region: "EU" },
  { symbol: "ATCO-A.ST", name: "Atlas Copco", sector: "Industrie", region: "EU" },
  { symbol: "VOLV-B.ST", name: "Volvo", sector: "Industrie", region: "EU" },
  { symbol: "ASSA-B.ST", name: "Assa Abloy", sector: "Industrie", region: "EU" },
  { symbol: "HEXA-B.ST", name: "Hexagon", sector: "Technologie", region: "EU" },
  { symbol: "INVE-B.ST", name: "Investor", sector: "Finanzen", region: "EU" },
  { symbol: "SEB-A.ST", name: "SEB", sector: "Finanzen", region: "EU" },
  { symbol: "SHB-A.ST", name: "Handelsbanken", sector: "Finanzen", region: "EU" },
  { symbol: "SWED-A.ST", name: "Swedbank", sector: "Finanzen", region: "EU" },
  { symbol: "NDA-SE.ST", name: "Nordea", sector: "Finanzen", region: "EU" },
  { symbol: "ERIC-B.ST", name: "Ericsson", sector: "Technologie", region: "EU" },
  { symbol: "HM-B.ST", name: "H&M", sector: "Konsum", region: "EU" },
  { symbol: "ELUX-B.ST", name: "Electrolux", sector: "Konsum", region: "EU" },
  { symbol: "SKF-B.ST", name: "SKF", sector: "Industrie", region: "EU" },
  { symbol: "ALFA.ST", name: "Alfa Laval", sector: "Industrie", region: "EU" },
  { symbol: "TEL2-B.ST", name: "Tele2", sector: "Technologie", region: "EU" },
  { symbol: "TELIA.ST", name: "Telia", sector: "Technologie", region: "EU" },
  { symbol: "BHP.L", name: "BHP Group", sector: "Rohstoffe", region: "UK" },
  { symbol: "AV.L", name: "Aviva", sector: "Finanzen", region: "UK" },
  { symbol: "CRH.L", name: "CRH", sector: "Industrie", region: "UK" },
  { symbol: "CCH.L", name: "Coca-Cola HBC", sector: "Konsum", region: "UK" },
  { symbol: "NEXT.L", name: "Next plc", sector: "Konsum", region: "UK" },
  { symbol: "BME.L", name: "B&M European Value", sector: "Konsum", region: "UK" },
  { symbol: "SAN.MC", name: "Banco Santander", sector: "Finanzen", region: "EU" },
  { symbol: "BBVA.MC", name: "BBVA", sector: "Finanzen", region: "EU" },
  { symbol: "REP.MC", name: "Repsol", sector: "Energie", region: "EU" },
  { symbol: "TEF.MC", name: "Telefonica", sector: "Technologie", region: "EU" },
  { symbol: "STLA.MI", name: "Stellantis", sector: "Konsum", region: "EU" },
  { symbol: "RACE.MI", name: "Ferrari", sector: "Konsum", region: "EU" },
  { symbol: "CDI.PA", name: "Christian Dior", sector: "Konsum", region: "EU" },
  { symbol: "EDF.PA", name: "EDF", sector: "Energie", region: "EU" },
  { symbol: "RDSA.AS", name: "Shell A", sector: "Energie", region: "EU" },
  { symbol: "ABN.AS", name: "ABN AMRO", sector: "Finanzen", region: "EU" },
  { symbol: "AGN.AS", name: "Aegon", sector: "Finanzen", region: "EU" },
  { symbol: "ASRNL.AS", name: "ASR Nederland", sector: "Finanzen", region: "EU" },
  { symbol: "KPN.AS", name: "KPN", sector: "Technologie", region: "EU" },
  { symbol: "DSM.AS", name: "DSM-Firmenich", sector: "Rohstoffe", region: "EU" },
  { symbol: "UMI.BR", name: "Umicore", sector: "Rohstoffe", region: "EU" },
  { symbol: "KBC.BR", name: "KBC Group", sector: "Finanzen", region: "EU" },
  { symbol: "AGS.BR", name: "Ageas", sector: "Finanzen", region: "EU" },
  { symbol: "UCB.BR", name: "UCB", sector: "Gesundheit", region: "EU" },
  { symbol: "SOLB.BR", name: "Solvay", sector: "Rohstoffe", region: "EU" },
  { symbol: "ABI.BR", name: "AB InBev", sector: "Konsum", region: "EU" },
  { symbol: "PROX.BR", name: "Proximus", sector: "Technologie", region: "EU" },
  { symbol: "GBLB.BR", name: "Groupe Bruxelles Lambert", sector: "Finanzen", region: "EU" },
  { symbol: "CSGN.SW", name: "Credit Suisse", sector: "Finanzen", region: "EU" },
  { symbol: "SIK.SW", name: "Sika", sector: "Rohstoffe", region: "EU" },
  { symbol: "RICHEMONT.SW", name: "Richemont", sector: "Konsum", region: "EU" },
  { symbol: "ADEN.SW", name: "Adecco", sector: "Industrie", region: "EU" },
  { symbol: "6752.T", name: "Panasonic", sector: "Technologie", region: "JP" },
  { symbol: "6502.T", name: "Toshiba", sector: "Industrie", region: "JP" },
  { symbol: "6503.T", name: "Mitsubishi Electric", sector: "Industrie", region: "JP" },
  { symbol: "6920.T", name: "Lasertec", sector: "Technologie", region: "JP" },
  { symbol: "4523.T", name: "Eisai", sector: "Gesundheit", region: "JP" },
  { symbol: "4568.T", name: "Daiichi Sankyo", sector: "Gesundheit", region: "JP" },
  { symbol: "8766.T", name: "Tokio Marine", sector: "Finanzen", region: "JP" },
  { symbol: "8591.T", name: "ORIX", sector: "Finanzen", region: "JP" },
  { symbol: "9020.T", name: "East Japan Railway", sector: "Industrie", region: "JP" },
  { symbol: "9022.T", name: "Central Japan Railway", sector: "Industrie", region: "JP" },
  { symbol: "3382.T", name: "Seven & i Holdings", sector: "Konsum", region: "JP" },
  { symbol: "8267.T", name: "Aeon", sector: "Konsum", region: "JP" },
  { symbol: "2914.T", name: "Japan Tobacco", sector: "Konsum", region: "JP" },
  { symbol: "2502.T", name: "Asahi Group", sector: "Konsum", region: "JP" },
  { symbol: "2503.T", name: "Kirin Holdings", sector: "Konsum", region: "JP" },
  { symbol: "4901.T", name: "Fujifilm", sector: "Technologie", region: "JP" },
  { symbol: "4519.T", name: "Chugai Pharmaceutical", sector: "Gesundheit", region: "JP" },
  { symbol: "4543.T", name: "Terumo", sector: "Gesundheit", region: "JP" },
  { symbol: "6098.T", name: "Recruit Holdings", sector: "Industrie", region: "JP" },
  { symbol: "6178.T", name: "Japan Post Holdings", sector: "Finanzen", region: "JP" },
  { symbol: "7011.T", name: "Mitsubishi Heavy", sector: "Industrie", region: "JP" },
  { symbol: "7012.T", name: "Kawasaki Heavy", sector: "Industrie", region: "JP" },
  { symbol: "7013.T", name: "IHI Corp", sector: "Industrie", region: "JP" },
  { symbol: "1605.T", name: "Inpex", sector: "Energie", region: "JP" },
  { symbol: "5020.T", name: "ENEOS Holdings", sector: "Energie", region: "JP" },
  { symbol: "9501.T", name: "TEPCO", sector: "Energie", region: "JP" },
  { symbol: "9503.T", name: "Kansai Electric", sector: "Energie", region: "JP" },
  { symbol: "9531.T", name: "Tokyo Gas", sector: "Energie", region: "JP" },
  { symbol: "9532.T", name: "Osaka Gas", sector: "Energie", region: "JP" },
  { symbol: "TME", name: "Tencent Music", sector: "Technologie", region: "JP" },
  { symbol: "IQ", name: "iQIYI", sector: "Technologie", region: "JP" },
  { symbol: "VIPS", name: "Vipshop", sector: "Konsum", region: "JP" },
  { symbol: "YMM", name: "Full Truck Alliance", sector: "Industrie", region: "JP" },
  { symbol: "BEKE", name: "KE Holdings", sector: "Finanzen", region: "JP" },
  { symbol: "ZK", name: "ZEEKR", sector: "Konsum", region: "JP" },
  { symbol: "LX", name: "LexinFintech", sector: "Finanzen", region: "JP" },
  { symbol: "FUTU", name: "Futu Holdings", sector: "Finanzen", region: "JP" },
  { symbol: "TIGR", name: "UP Fintech", sector: "Finanzen", region: "JP" },
  { symbol: "TAL", name: "TAL Education", sector: "Konsum", region: "JP" },
  { symbol: "EDU", name: "New Oriental Education", sector: "Konsum", region: "JP" },
  { symbol: "BZ", name: "Kanzhun", sector: "Industrie", region: "JP" },
  { symbol: "DOYU", name: "DouYu", sector: "Technologie", region: "JP" },
  { symbol: "HUYA", name: "HUYA", sector: "Technologie", region: "JP" },
  { symbol: "YY", name: "JOYY", sector: "Technologie", region: "JP" },
  { symbol: "WB", name: "Weibo", sector: "Technologie", region: "JP" },
  { symbol: "DIDI", name: "DiDi Global", sector: "Konsum", region: "JP" },
  { symbol: "ZTO", name: "ZTO Express", sector: "Industrie", region: "JP" },
  { symbol: "LFC", name: "China Life Insurance", sector: "Finanzen", region: "JP" },
  { symbol: "PNGAY", name: "Ping An Insurance", sector: "Finanzen", region: "JP" },
  { symbol: "CHL", name: "China Mobile", sector: "Technologie", region: "JP" },
  { symbol: "HKD", name: "AMTD Digital", sector: "Finanzen", region: "JP" },
  { symbol: "RLX", name: "RLX Technology", sector: "Konsum", region: "JP" },
  { symbol: "YALA", name: "Yalla Group", sector: "Technologie", region: "JP" },
  { symbol: "RIO.AX", name: "Rio Tinto AU", sector: "Rohstoffe", region: "JP" },
  { symbol: "TCL.AX", name: "Transurban", sector: "Industrie", region: "JP" },
  { symbol: "STO.AX", name: "Santos", sector: "Energie", region: "JP" },
  { symbol: "WDS.AX", name: "Woodside Energy", sector: "Energie", region: "JP" },
  { symbol: "ORG.AX", name: "Origin Energy", sector: "Energie", region: "JP" },
  { symbol: "QAN.AX", name: "Qantas", sector: "Industrie", region: "JP" },
  { symbol: "MIN.AX", name: "Mineral Resources", sector: "Rohstoffe", region: "JP" },
  { symbol: "PLS.AX", name: "Pilbara Minerals", sector: "Rohstoffe", region: "JP" },
  { symbol: "IGO.AX", name: "IGO Limited", sector: "Rohstoffe", region: "JP" },
  { symbol: "CXO.AX", name: "Core Lithium", sector: "Rohstoffe", region: "JP" },
  { symbol: "LTR.AX", name: "Liontown Resources", sector: "Rohstoffe", region: "JP" },
  { symbol: "NST.AX", name: "Northern Star", sector: "Rohstoffe", region: "JP" },
  { symbol: "EVN.AX", name: "Evolution Mining", sector: "Rohstoffe", region: "JP" },
  { symbol: "NCM.AX", name: "Newcrest Mining", sector: "Rohstoffe", region: "JP" },
  { symbol: "RDY", name: "Dr Reddys", sector: "Gesundheit", region: "JP" },
  { symbol: "SIFY", name: "Sify Technologies", sector: "Technologie", region: "JP" },
  { symbol: "MMYT", name: "MakeMyTrip", sector: "Konsum", region: "JP" },
  { symbol: "YATRA", name: "Yatra Online", sector: "Konsum", region: "JP" },
  { symbol: "AZURE", name: "Azure Power", sector: "Energie", region: "JP" },
  { symbol: "VEDL", name: "Vedanta", sector: "Rohstoffe", region: "JP" },
  { symbol: "HUT", name: "Hut 8", sector: "Technologie", region: "US" },
  { symbol: "HIVE", name: "HIVE Digital", sector: "Technologie", region: "US" },
  { symbol: "BITF", name: "Bitfarms", sector: "Technologie", region: "US" },
  { symbol: "WULF", name: "TeraWulf", sector: "Technologie", region: "US" },
  { symbol: "CAN", name: "Canaan", sector: "Technologie", region: "US" },
  { symbol: "EBON", name: "Ebang International", sector: "Technologie", region: "US" },
  { symbol: "GBTC", name: "Grayscale Bitcoin Trust", sector: "Finanzen", region: "US" },
  { symbol: "BITB", name: "Bitwise Bitcoin", sector: "Finanzen", region: "US" },
  { symbol: "GRAB", name: "Grab Holdings", sector: "Technologie", region: "JP" },
  { symbol: "SE", name: "Sea Limited", sector: "Technologie", region: "JP" },
  { symbol: "MELI", name: "MercadoLibre", sector: "Konsum", region: "US" },
  { symbol: "NU", name: "Nu Holdings", sector: "Finanzen", region: "US" },
  { symbol: "STNE", name: "StoneCo", sector: "Finanzen", region: "US" },
  { symbol: "PAGS", name: "PagSeguro", sector: "Finanzen", region: "US" },
  { symbol: "VALE", name: "Vale", sector: "Rohstoffe", region: "US" },
  { symbol: "ITUB", name: "Itau Unibanco", sector: "Finanzen", region: "US" },
  { symbol: "BBD", name: "Banco Bradesco", sector: "Finanzen", region: "US" },
  { symbol: "PBR", name: "Petrobras", sector: "Energie", region: "US" },
  { symbol: "EBR", name: "Eletrobras", sector: "Energie", region: "US" },
  { symbol: "VIV", name: "Telefonica Brasil", sector: "Technologie", region: "US" },
  { symbol: "ABEV", name: "Ambev", sector: "Konsum", region: "US" },
  { symbol: "SUZ", name: "Suzano", sector: "Rohstoffe", region: "US" },
  { symbol: "GGB", name: "Gerdau", sector: "Rohstoffe", region: "US" },
  { symbol: "BSAC", name: "Banco Santander Chile", sector: "Finanzen", region: "US" },
  { symbol: "CIB", name: "Bancolombia", sector: "Finanzen", region: "US" },
  { symbol: "AMX", name: "America Movil", sector: "Technologie", region: "US" },
  { symbol: "FMX", name: "Fomento Economico Mexicano", sector: "Konsum", region: "US" },
  { symbol: "KOF", name: "Coca-Cola FEMSA", sector: "Konsum", region: "US" },
  { symbol: "GFNORTEO.MX", name: "Grupo Financiero Banorte", sector: "Finanzen", region: "US" },
  { symbol: "WALMEX.MX", name: "Walmart Mexico", sector: "Konsum", region: "US" },
  { symbol: "CEMEX", name: "Cemex", sector: "Rohstoffe", region: "US" },
  { symbol: "TX", name: "Ternium", sector: "Rohstoffe", region: "US" },
  { symbol: "SCCO", name: "Southern Copper", sector: "Rohstoffe", region: "US" },
  { symbol: "ASR", name: "Grupo Aeroportuario del Sureste", sector: "Industrie", region: "US" },
  { symbol: "OMAB", name: "Centro Norte Airport", sector: "Industrie", region: "US" },
];
