import type { CountryExtras } from "./types";

export const COUNTRY_EXTRAS: Record<string, CountryExtras> = {
  "United States of America": { influenceScore: 10, influenceWhy: "Reserve currency, deepest capital markets, global rate-setter via the Fed.", globalRole: "Sets global liquidity, risk appetite and the price of money.", strengthIndex: { government: "Strong", policy: "Medium", economy: "Strong", geopoliticalStability: 7, investorConfidence: "High" }, transmission: ["Fed policy → global liquidity and EM capital flows.", "USD strength → commodity prices and EM debt sustainability.", "S&P 500 → global equity risk sentiment."] },
  China: { influenceScore: 9, influenceWhy: "Marginal buyer of industrial commodities; core node in global manufacturing.", globalRole: "Drives commodity demand and global goods-price disinflation.", strengthIndex: { government: "Strong", policy: "Medium", economy: "Medium", geopoliticalStability: 5, investorConfidence: "Medium" }, transmission: ["Property + credit cycle → iron ore, copper, steel.", "Export prices → global goods CPI.", "CNY fixing → Asian FX complex."] },
  Germany: { influenceScore: 7, influenceWhy: "Eurozone industrial engine; bellwether for European manufacturing.", globalRole: "Barometer for the European industrial cycle.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Medium", geopoliticalStability: 7, investorConfidence: "Medium" }, transmission: ["DAX → EU equity sentiment.", "Bund yields → EU rate anchor.", "Auto/chem orders → global industrial pulse."] },
  Japan: { influenceScore: 8, influenceWhy: "World's largest creditor; BoJ shifts move global carry & bond markets.", globalRole: "Global liquidity provider via yen-funded carry trades.", strengthIndex: { government: "Strong", policy: "High", economy: "Medium", geopoliticalStability: 8, investorConfidence: "High" }, transmission: ["BoJ policy → USD/JPY and global bond yields.", "JGB repatriation → Treasury demand.", "Yen strength → global risk-off signal."] },
  "United Kingdom": { influenceScore: 7, influenceWhy: "Major financial centre; GBP and Gilts react to global risk and BoE policy.", globalRole: "Bridge market between US and EU; financial-services hub.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Medium", geopoliticalStability: 7, investorConfidence: "Medium" }, transmission: ["BoE expectations → GBP.", "Gilt yields → European rate cross-currents.", "London FX volumes → global liquidity."] },
  France: { influenceScore: 6, influenceWhy: "Second-largest eurozone economy; fiscal & political risk drives EUR risk premium.", globalRole: "Sets eurozone political risk premium.", strengthIndex: { government: "Weak", policy: "Low", economy: "Medium", geopoliticalStability: 6, investorConfidence: "Medium" }, transmission: ["OAT–Bund spread → EU sovereign risk.", "CAC40 → EU luxury/credit beta.", "Politics → EUR risk premium."] },
  India: { influenceScore: 7, influenceWhy: "Fastest-growing major economy; magnet for EM equity inflows.", globalRole: "EM growth anchor and China-diversification beneficiary.", strengthIndex: { government: "Strong", policy: "High", economy: "Strong", geopoliticalStability: 7, investorConfidence: "High" }, transmission: ["Domestic growth → EM equity flows.", "Oil/gold imports → current-account FX impact.", "Tech services → global IT spend gauge."] },
  Russia: { influenceScore: 6, influenceWhy: "Top-tier energy and grains exporter; geopolitical tail-risk node.", globalRole: "Marginal supplier of crude, gas and wheat outside Western system.", strengthIndex: { government: "Strong", policy: "Medium", economy: "Medium", geopoliticalStability: 3, investorConfidence: "Low" }, transmission: ["Crude/gas exports → European energy prices.", "Grain exports → global food inflation.", "Geopolitics → safe-haven flows."] },
  Brazil: { influenceScore: 6, influenceWhy: "Top supplier of iron ore, soy and sugar; high-real-rate EM benchmark.", globalRole: "LatAm sentiment and soft-commodity supplier.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Medium", geopoliticalStability: 6, investorConfidence: "Medium" }, transmission: ["BCB policy → EM carry trades.", "Iron/soy exports → China-linked flow.", "Fiscal news → BRL volatility."] },
  Canada: { influenceScore: 5, influenceWhy: "G7 commodity exporter; high-beta proxy to the US consumer and oil.", globalRole: "US consumer proxy + crude/uranium supplier.", strengthIndex: { government: "Strong", policy: "High", economy: "Medium", geopoliticalStability: 8, investorConfidence: "High" }, transmission: ["BoC tracks Fed → CAD correlated with oil.", "WCS crude → North-American energy balance.", "Housing → consumer signal."] },
  "Saudi Arabia": { influenceScore: 8, influenceWhy: "OPEC+ leader and swing producer — single-handedly moves Brent.", globalRole: "Sets the global oil price floor.", strengthIndex: { government: "Strong", policy: "High", economy: "Strong", geopoliticalStability: 6, investorConfidence: "Medium" }, transmission: ["OPEC+ output → Brent crude.", "PIF flows → global private markets.", "Petrodollar recycling → US Treasuries."] },
  "South Korea": { influenceScore: 7, influenceWhy: "Backbone of global memory & AI semiconductor supply chain.", globalRole: "Leading indicator of global tech demand.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Strong", geopoliticalStability: 6, investorConfidence: "Medium" }, transmission: ["Memory pricing → global tech earnings.", "KRW → Asian risk barometer.", "Exports → global trade pulse."] },
  Mexico: { influenceScore: 6, influenceWhy: "Nearshoring's top winner; high-real-rate EM carry favourite.", globalRole: "Industrial gateway to the US market.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Medium", geopoliticalStability: 5, investorConfidence: "Medium" }, transmission: ["Banxico → MXN carry.", "USMCA flows → industrial FDI.", "Remittances → US labour proxy."] },
  Australia: { influenceScore: 6, influenceWhy: "Largest iron ore and major LNG exporter; AUD = China-demand proxy.", globalRole: "Real-time gauge of Chinese industrial demand.", strengthIndex: { government: "Strong", policy: "High", economy: "Strong", geopoliticalStability: 8, investorConfidence: "High" }, transmission: ["Iron ore → AUD.", "LNG exports → Asian energy balance.", "RBA → AUD/USD vs Fed."] },
  Argentina: { influenceScore: 4, influenceWhy: "Frontier reform story; influences EM risk premium and sovereign spreads.", globalRole: "EM reform bellwether; lithium & soy supplier.", strengthIndex: { government: "Moderate", policy: "Medium", economy: "Weak", geopoliticalStability: 5, investorConfidence: "Medium" }, transmission: ["Disinflation pace → sovereign spreads.", "Lithium → battery supply chain.", "FX reserves → EM contagion risk."] },
};
