/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as SignaleRouteImport } from './routes/signale'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MaerkteRouteImport } from './routes/maerkte'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukteIndexRouteImport } from './routes/produkte.index'
import { Route as ProdukteSymbolRouteImport } from './routes/produkte.$symbol'
import { Route as ApiPublicQuoteRouteImport } from './routes/api/public/quote'
import { Route as ApiPublicNewsSentimentRouteImport } from './routes/api/public/news-sentiment'
import { Route as ApiPublicCandlesRouteImport } from './routes/api/public/candles'
import { Route as ApiPublicAgentChatRouteImport } from './routes/api/public/agent-chat'

const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaleRoute = SignaleRouteImport.update({
  id: '/signale',
  path: '/signale',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MaerkteRoute = MaerkteRouteImport.update({
  id: '/maerkte',
  path: '/maerkte',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteIndexRoute = ProdukteIndexRouteImport.update({
  id: '/produkte/',
  path: '/produkte/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteSymbolRoute = ProdukteSymbolRouteImport.update({
  id: '/produkte/$symbol',
  path: '/produkte/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRoute = ApiPublicQuoteRouteImport.update({
  id: '/api/public/quote',
  path: '/api/public/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsSentimentRoute = ApiPublicNewsSentimentRouteImport.update({
  id: '/api/public/news-sentiment',
  path: '/api/public/news-sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCandlesRoute = ApiPublicCandlesRouteImport.update({
  id: '/api/public/candles',
  path: '/api/public/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentChatRoute = ApiPublicAgentChatRouteImport.update({
  id: '/api/public/agent-chat',
  path: '/api/public/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte/': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte/': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/heatmap'
    | '/kalender'
    | '/maerkte'
    | '/news'
    | '/portfolio'
    | '/signale'
    | '/war-room'
    | '/produkte/$symbol'
    | '/produkte/'
    | '/api/public/agent-chat'
    | '/api/public/candles'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/heatmap'
    | '/kalender'
    | '/maerkte'
    | '/news'
    | '/portfolio'
    | '/signale'
    | '/war-room'
    | '/produkte/$symbol'
    | '/produkte'
    | '/api/public/agent-chat'
    | '/api/public/candles'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/heatmap'
    | '/kalender'
    | '/maerkte'
    | '/news'
    | '/portfolio'
    | '/signale'
    | '/war-room'
    | '/produkte/$symbol'
    | '/produkte/'
    | '/api/public/agent-chat'
    | '/api/public/candles'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AlertsRoute: typeof AlertsRoute
  AnalyseRoute: typeof AnalyseRoute
  BacktestRoute: typeof BacktestRoute
  EinstellungenRoute: typeof EinstellungenRoute
  HeatmapRoute: typeof HeatmapRoute
  KalenderRoute: typeof KalenderRoute
  MaerkteRoute: typeof MaerkteRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  SignaleRoute: typeof SignaleRoute
  WarRoomRoute: typeof WarRoomRoute
  ProdukteSymbolRoute: typeof ProdukteSymbolRoute
  ProdukteIndexRoute: typeof ProdukteIndexRoute
  ApiPublicAgentChatRoute: typeof ApiPublicAgentChatRoute
  ApiPublicCandlesRoute: typeof ApiPublicCandlesRoute
  ApiPublicNewsSentimentRoute: typeof ApiPublicNewsSentimentRoute
  ApiPublicQuoteRoute: typeof ApiPublicQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signale': {
      id: '/signale'
      path: '/signale'
      fullPath: '/signale'
      preLoaderRoute: typeof SignaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maerkte': {
      id: '/maerkte'
      path: '/maerkte'
      fullPath: '/maerkte'
      preLoaderRoute: typeof MaerkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte/': {
      id: '/produkte/'
      path: '/produkte'
      fullPath: '/produkte/'
      preLoaderRoute: typeof ProdukteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte/$symbol': {
      id: '/produkte/$symbol'
      path: '/produkte/$symbol'
      fullPath: '/produkte/$symbol'
      preLoaderRoute: typeof ProdukteSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote': {
      id: '/api/public/quote'
      path: '/api/public/quote'
      fullPath: '/api/public/quote'
      preLoaderRoute: typeof ApiPublicQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news-sentiment': {
      id: '/api/public/news-sentiment'
      path: '/api/public/news-sentiment'
      fullPath: '/api/public/news-sentiment'
      preLoaderRoute: typeof ApiPublicNewsSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/candles': {
      id: '/api/public/candles'
      path: '/api/public/candles'
      fullPath: '/api/public/candles'
      preLoaderRoute: typeof ApiPublicCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-chat': {
      id: '/api/public/agent-chat'
      path: '/api/public/agent-chat'
      fullPath: '/api/public/agent-chat'
      preLoaderRoute: typeof ApiPublicAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AlertsRoute: AlertsRoute,
  AnalyseRoute: AnalyseRoute,
  BacktestRoute: BacktestRoute,
  EinstellungenRoute: EinstellungenRoute,
  HeatmapRoute: HeatmapRoute,
  KalenderRoute: KalenderRoute,
  MaerkteRoute: MaerkteRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  SignaleRoute: SignaleRoute,
  WarRoomRoute: WarRoomRoute,
  ProdukteSymbolRoute: ProdukteSymbolRoute,
  ProdukteIndexRoute: ProdukteIndexRoute,
  ApiPublicAgentChatRoute: ApiPublicAgentChatRoute,
  ApiPublicCandlesRoute: ApiPublicCandlesRoute,
  ApiPublicNewsSentimentRoute: ApiPublicNewsSentimentRoute,
  ApiPublicQuoteRoute: ApiPublicQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
