/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as SignaleRouteImport } from './routes/signale'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PasswortZuruecksetzenRouteImport } from './routes/passwort-zuruecksetzen'
import { Route as PasswortVergessenRouteImport } from './routes/passwort-vergessen'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MaerkteRouteImport } from './routes/maerkte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HandelsprofilRouteImport } from './routes/handelsprofil'
import { Route as ExplainTradeRouteImport } from './routes/explain-trade'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiLearningRouteImport } from './routes/ai-learning'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukteIndexRouteImport } from './routes/produkte.index'
import { Route as ProdukteSymbolRouteImport } from './routes/produkte.$symbol'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicQuoteRouteImport } from './routes/api/public/quote'
import { Route as ApiPublicNewsSentimentRouteImport } from './routes/api/public/news-sentiment'
import { Route as ApiPublicExplainTradeRouteImport } from './routes/api/public/explain-trade'
import { Route as ApiPublicExplainConceptRouteImport } from './routes/api/public/explain-concept'
import { Route as ApiPublicCronEvaluateRouteImport } from './routes/api/public/cron-evaluate'
import { Route as ApiPublicCandlesRouteImport } from './routes/api/public/candles'
import { Route as ApiPublicAgentFeedbackRouteImport } from './routes/api/public/agent-feedback'
import { Route as ApiPublicAgentChatRouteImport } from './routes/api/public/agent-chat'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaleRoute = SignaleRouteImport.update({
  id: '/signale',
  path: '/signale',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortZuruecksetzenRoute = PasswortZuruecksetzenRouteImport.update({
  id: '/passwort-zuruecksetzen',
  path: '/passwort-zuruecksetzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortVergessenRoute = PasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MaerkteRoute = MaerkteRouteImport.update({
  id: '/maerkte',
  path: '/maerkte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HandelsprofilRoute = HandelsprofilRouteImport.update({
  id: '/handelsprofil',
  path: '/handelsprofil',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainTradeRoute = ExplainTradeRouteImport.update({
  id: '/explain-trade',
  path: '/explain-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLearningRoute = AiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteIndexRoute = ProdukteIndexRouteImport.update({
  id: '/produkte/',
  path: '/produkte/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteSymbolRoute = ProdukteSymbolRouteImport.update({
  id: '/produkte/$symbol',
  path: '/produkte/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRoute = ApiPublicQuoteRouteImport.update({
  id: '/api/public/quote',
  path: '/api/public/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsSentimentRoute = ApiPublicNewsSentimentRouteImport.update({
  id: '/api/public/news-sentiment',
  path: '/api/public/news-sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExplainTradeRoute = ApiPublicExplainTradeRouteImport.update({
  id: '/api/public/explain-trade',
  path: '/api/public/explain-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExplainConceptRoute = ApiPublicExplainConceptRouteImport.update({
  id: '/api/public/explain-concept',
  path: '/api/public/explain-concept',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEvaluateRoute = ApiPublicCronEvaluateRouteImport.update({
  id: '/api/public/cron-evaluate',
  path: '/api/public/cron-evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCandlesRoute = ApiPublicCandlesRouteImport.update({
  id: '/api/public/candles',
  path: '/api/public/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentFeedbackRoute = ApiPublicAgentFeedbackRouteImport.update({
  id: '/api/public/agent-feedback',
  path: '/api/public/agent-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentChatRoute = ApiPublicAgentChatRouteImport.update({
  id: '/api/public/agent-chat',
  path: '/api/public/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/ai-learning': typeof AiLearningRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/explain-trade': typeof ExplainTradeRoute
  '/handelsprofil': typeof HandelsprofilRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/portfolio': typeof PortfolioRoute
  '/preise': typeof PreiseRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/welcome': typeof WelcomeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte/': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/agent-feedback': typeof ApiPublicAgentFeedbackRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/cron-evaluate': typeof ApiPublicCronEvaluateRoute
  '/api/public/explain-concept': typeof ApiPublicExplainConceptRoute
  '/api/public/explain-trade': typeof ApiPublicExplainTradeRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/ai-learning': typeof AiLearningRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/explain-trade': typeof ExplainTradeRoute
  '/handelsprofil': typeof HandelsprofilRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/portfolio': typeof PortfolioRoute
  '/preise': typeof PreiseRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/welcome': typeof WelcomeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/agent-feedback': typeof ApiPublicAgentFeedbackRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/cron-evaluate': typeof ApiPublicCronEvaluateRoute
  '/api/public/explain-concept': typeof ApiPublicExplainConceptRoute
  '/api/public/explain-trade': typeof ApiPublicExplainTradeRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/ai-learning': typeof AiLearningRoute
  '/alerts': typeof AlertsRoute
  '/analyse': typeof AnalyseRoute
  '/backtest': typeof BacktestRoute
  '/einstellungen': typeof EinstellungenRoute
  '/explain-trade': typeof ExplainTradeRoute
  '/handelsprofil': typeof HandelsprofilRoute
  '/heatmap': typeof HeatmapRoute
  '/kalender': typeof KalenderRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/maerkte': typeof MaerkteRoute
  '/news': typeof NewsRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/portfolio': typeof PortfolioRoute
  '/preise': typeof PreiseRoute
  '/signale': typeof SignaleRoute
  '/war-room': typeof WarRoomRoute
  '/welcome': typeof WelcomeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$symbol': typeof ProdukteSymbolRoute
  '/produkte/': typeof ProdukteIndexRoute
  '/api/public/agent-chat': typeof ApiPublicAgentChatRoute
  '/api/public/agent-feedback': typeof ApiPublicAgentFeedbackRoute
  '/api/public/candles': typeof ApiPublicCandlesRoute
  '/api/public/cron-evaluate': typeof ApiPublicCronEvaluateRoute
  '/api/public/explain-concept': typeof ApiPublicExplainConceptRoute
  '/api/public/explain-trade': typeof ApiPublicExplainTradeRoute
  '/api/public/news-sentiment': typeof ApiPublicNewsSentimentRoute
  '/api/public/quote': typeof ApiPublicQuoteRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/ai-learning'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/explain-trade'
    | '/handelsprofil'
    | '/heatmap'
    | '/kalender'
    | '/konto'
    | '/login'
    | '/maerkte'
    | '/news'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/portfolio'
    | '/preise'
    | '/signale'
    | '/war-room'
    | '/welcome'
    | '/checkout/return'
    | '/produkte/$symbol'
    | '/produkte/'
    | '/api/public/agent-chat'
    | '/api/public/agent-feedback'
    | '/api/public/candles'
    | '/api/public/cron-evaluate'
    | '/api/public/explain-concept'
    | '/api/public/explain-trade'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/ai-learning'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/explain-trade'
    | '/handelsprofil'
    | '/heatmap'
    | '/kalender'
    | '/konto'
    | '/login'
    | '/maerkte'
    | '/news'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/portfolio'
    | '/preise'
    | '/signale'
    | '/war-room'
    | '/welcome'
    | '/checkout/return'
    | '/produkte/$symbol'
    | '/produkte'
    | '/api/public/agent-chat'
    | '/api/public/agent-feedback'
    | '/api/public/candles'
    | '/api/public/cron-evaluate'
    | '/api/public/explain-concept'
    | '/api/public/explain-trade'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/ai-learning'
    | '/alerts'
    | '/analyse'
    | '/backtest'
    | '/einstellungen'
    | '/explain-trade'
    | '/handelsprofil'
    | '/heatmap'
    | '/kalender'
    | '/konto'
    | '/login'
    | '/maerkte'
    | '/news'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/portfolio'
    | '/preise'
    | '/signale'
    | '/war-room'
    | '/welcome'
    | '/checkout/return'
    | '/produkte/$symbol'
    | '/produkte/'
    | '/api/public/agent-chat'
    | '/api/public/agent-feedback'
    | '/api/public/candles'
    | '/api/public/cron-evaluate'
    | '/api/public/explain-concept'
    | '/api/public/explain-trade'
    | '/api/public/news-sentiment'
    | '/api/public/quote'
    | '/api/public/search'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AiLearningRoute: typeof AiLearningRoute
  AlertsRoute: typeof AlertsRoute
  AnalyseRoute: typeof AnalyseRoute
  BacktestRoute: typeof BacktestRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ExplainTradeRoute: typeof ExplainTradeRoute
  HandelsprofilRoute: typeof HandelsprofilRoute
  HeatmapRoute: typeof HeatmapRoute
  KalenderRoute: typeof KalenderRoute
  KontoRoute: typeof KontoRoute
  LoginRoute: typeof LoginRoute
  MaerkteRoute: typeof MaerkteRoute
  NewsRoute: typeof NewsRoute
  PasswortVergessenRoute: typeof PasswortVergessenRoute
  PasswortZuruecksetzenRoute: typeof PasswortZuruecksetzenRoute
  PortfolioRoute: typeof PortfolioRoute
  PreiseRoute: typeof PreiseRoute
  SignaleRoute: typeof SignaleRoute
  WarRoomRoute: typeof WarRoomRoute
  WelcomeRoute: typeof WelcomeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ProdukteSymbolRoute: typeof ProdukteSymbolRoute
  ProdukteIndexRoute: typeof ProdukteIndexRoute
  ApiPublicAgentChatRoute: typeof ApiPublicAgentChatRoute
  ApiPublicAgentFeedbackRoute: typeof ApiPublicAgentFeedbackRoute
  ApiPublicCandlesRoute: typeof ApiPublicCandlesRoute
  ApiPublicCronEvaluateRoute: typeof ApiPublicCronEvaluateRoute
  ApiPublicExplainConceptRoute: typeof ApiPublicExplainConceptRoute
  ApiPublicExplainTradeRoute: typeof ApiPublicExplainTradeRoute
  ApiPublicNewsSentimentRoute: typeof ApiPublicNewsSentimentRoute
  ApiPublicQuoteRoute: typeof ApiPublicQuoteRoute
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signale': {
      id: '/signale'
      path: '/signale'
      fullPath: '/signale'
      preLoaderRoute: typeof SignaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-zuruecksetzen': {
      id: '/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof PasswortZuruecksetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-vergessen': {
      id: '/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof PasswortVergessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maerkte': {
      id: '/maerkte'
      path: '/maerkte'
      fullPath: '/maerkte'
      preLoaderRoute: typeof MaerkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handelsprofil': {
      id: '/handelsprofil'
      path: '/handelsprofil'
      fullPath: '/handelsprofil'
      preLoaderRoute: typeof HandelsprofilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain-trade': {
      id: '/explain-trade'
      path: '/explain-trade'
      fullPath: '/explain-trade'
      preLoaderRoute: typeof ExplainTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-learning': {
      id: '/ai-learning'
      path: '/ai-learning'
      fullPath: '/ai-learning'
      preLoaderRoute: typeof AiLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte/': {
      id: '/produkte/'
      path: '/produkte'
      fullPath: '/produkte/'
      preLoaderRoute: typeof ProdukteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte/$symbol': {
      id: '/produkte/$symbol'
      path: '/produkte/$symbol'
      fullPath: '/produkte/$symbol'
      preLoaderRoute: typeof ProdukteSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote': {
      id: '/api/public/quote'
      path: '/api/public/quote'
      fullPath: '/api/public/quote'
      preLoaderRoute: typeof ApiPublicQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news-sentiment': {
      id: '/api/public/news-sentiment'
      path: '/api/public/news-sentiment'
      fullPath: '/api/public/news-sentiment'
      preLoaderRoute: typeof ApiPublicNewsSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/explain-trade': {
      id: '/api/public/explain-trade'
      path: '/api/public/explain-trade'
      fullPath: '/api/public/explain-trade'
      preLoaderRoute: typeof ApiPublicExplainTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/explain-concept': {
      id: '/api/public/explain-concept'
      path: '/api/public/explain-concept'
      fullPath: '/api/public/explain-concept'
      preLoaderRoute: typeof ApiPublicExplainConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-evaluate': {
      id: '/api/public/cron-evaluate'
      path: '/api/public/cron-evaluate'
      fullPath: '/api/public/cron-evaluate'
      preLoaderRoute: typeof ApiPublicCronEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/candles': {
      id: '/api/public/candles'
      path: '/api/public/candles'
      fullPath: '/api/public/candles'
      preLoaderRoute: typeof ApiPublicCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-feedback': {
      id: '/api/public/agent-feedback'
      path: '/api/public/agent-feedback'
      fullPath: '/api/public/agent-feedback'
      preLoaderRoute: typeof ApiPublicAgentFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-chat': {
      id: '/api/public/agent-chat'
      path: '/api/public/agent-chat'
      fullPath: '/api/public/agent-chat'
      preLoaderRoute: typeof ApiPublicAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AiLearningRoute: AiLearningRoute,
  AlertsRoute: AlertsRoute,
  AnalyseRoute: AnalyseRoute,
  BacktestRoute: BacktestRoute,
  EinstellungenRoute: EinstellungenRoute,
  ExplainTradeRoute: ExplainTradeRoute,
  HandelsprofilRoute: HandelsprofilRoute,
  HeatmapRoute: HeatmapRoute,
  KalenderRoute: KalenderRoute,
  KontoRoute: KontoRoute,
  LoginRoute: LoginRoute,
  MaerkteRoute: MaerkteRoute,
  NewsRoute: NewsRoute,
  PasswortVergessenRoute: PasswortVergessenRoute,
  PasswortZuruecksetzenRoute: PasswortZuruecksetzenRoute,
  PortfolioRoute: PortfolioRoute,
  PreiseRoute: PreiseRoute,
  SignaleRoute: SignaleRoute,
  WarRoomRoute: WarRoomRoute,
  WelcomeRoute: WelcomeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ProdukteSymbolRoute: ProdukteSymbolRoute,
  ProdukteIndexRoute: ProdukteIndexRoute,
  ApiPublicAgentChatRoute: ApiPublicAgentChatRoute,
  ApiPublicAgentFeedbackRoute: ApiPublicAgentFeedbackRoute,
  ApiPublicCandlesRoute: ApiPublicCandlesRoute,
  ApiPublicCronEvaluateRoute: ApiPublicCronEvaluateRoute,
  ApiPublicExplainConceptRoute: ApiPublicExplainConceptRoute,
  ApiPublicExplainTradeRoute: ApiPublicExplainTradeRoute,
  ApiPublicNewsSentimentRoute: ApiPublicNewsSentimentRoute,
  ApiPublicQuoteRoute: ApiPublicQuoteRoute,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
